### ISSUE TITLE
Outgoing HTTPS via proxy

### ISSUE THREAD

**Issue by Wykiki** [codecentric/helm-charts#108]
Hello,

I encounter a problem with the chart, I am not able to forward Keycloak's outgoing requests to a corporate proxy.

I already tried to give my proxy settings through environment variables and CLI argument :

```
-Dhttp.proxyHost=X.X.X.X -Dhttp.proxyPort=1234 -Dhttps.proxyHost=...
```

Other Java tools works nicely with those variables.

Digging in the doc, I found this [one about outgoing HTTPS requests](https://www.keycloak.org/docs/latest/server_installation/index.html#outgoing-http-requests).

Is there a way to configure those proxy settings via environment variables, or am I stuck maintening a ConfigMap to override one of the files quoted in the documentation ?

Thanks !

**Comment by Wykiki** [comment]
Solved my issue adding to the values.yaml :

```yaml
keycloak:
  cli:
    custom: |
      /subsystem=keycloak-server/spi=connectionsHttpClient/provider=default:write-attribute(name=properties.proxy-mappings,value=[".*\\.(google|microsoft)\\.com;http://<proxy_ip>:<proxy_port>"])
```

More fine tuning than the expected solution, but not documented very well I think.
