### ISSUE TITLE
404 page not found or SSL error when trying to connect

### ISSUE THREAD

**Issue by Ferdinanddb** [codecentric/helm-charts#110]
Hello, 

This is not a technical issue in the sense that I might just have a configuration problem... But if someone could help on that it would be very nice :-) !

So my context is:
I just followed and adapted this [tutorial](https://medium.com/@kvaps/adding-ldap-authentication-to-kubernetes-5c1f894a5a98) to my situation : I have a LDAP server and I managed to connect it to my k8s cluster (i've tested to sync users inside the freeIPA LDAP-server to Keycloak and it worked). After that I tried to deploy the example at the end with the following adapted code : 
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-dashboard-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-dashboard-proxy
    spec:
      containers:
      - args:
        - --listen=0.0.0.0:80
        - --discovery-url=http://10.0.9.9:8008/auth/realms/k8s
        - --client-id=k8s
        - --client-secret=XxXxXxXxXxXXXXXXXXXXXXxxxXx
        - --redirection-url=https://10.0.9.9:32715
        - --enable-refresh-tokens=true
        - --encryption-key=XXXxxxxXxxxXXXXXxxXX # didn't understand well the purpose of this
        - --upstream-url=https://10.0.9.9:32715 # this is the IP:port of my kubernetes-dashboard
        - --resources=uri=/*
        image: keycloak/keycloak-gatekeeper
        name: kubernetes-dashboard-proxy
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /oauth/health
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /oauth/health
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard-proxy
spec:
  externalIPs: 
  - 10.0.9.9
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 80
  selector:
    app: kubernetes-dashboard-proxy
  type: ClusterIP
```
So my problem is : when I reach https://10.0.9.9:8005, I can see the login page of kubernetes-dashboard. 
I tried to connect with dumb values and it says that the user is not recognized so it's good. 
After that, I tried with the user that I created in my freeIPA LDAP-server and I can see it was recognized cause it redirects me to the URL : `https://10.0.9.9:32715/oauth/callback?state=XxXXYYYyxxXXX&session_state=XxXXYYYyxxXXXzZzZzZ&code=XxXXYYYyxxXXXZzZZZZZZzyYYyYYYYYyYyYy` but what is displayed is `404 page not found`. 

When changing the `redirect-url` to https://10.0.9.9:8008 in the `containers.args` inside the deployment object I get an SSL error : SSL_ERROR_RX_RECORD_TOO_LONG. 

Also : when looking at the logs of the pod kubernetes-dashboard-proxy I can see this error :
1.5677769725986383e+09 error no session found in request, redirecting for authorization {"error": "authentication session not found"}

Did anyone have encountered this issue and would be able to help me :-)?
