### ISSUE TITLE
Mailhog: Ingress.extensions is invalid

### ISSUE THREAD

**Issue by tehKapa** [codecentric/helm-charts#139]
Hi! 
I enabled the ingress in Helm values file and I've this error:

`Error: failed to create resource: Ingress.extensions "mailhog" is invalid: spec.rules[0].host: Invalid value: "map[host:mailhog.mydomain.com paths:[/]]": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

 ```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: mailhog.mydomain.com
      paths: ["/"]

  tls:
    - hosts:
        - mailhog.mydomain.com
      secretName: mailhog-tls
```

Any ideas?

Helm: v2.16.0
Kubernetes: v1.15.5

**Comment by unguiculus** [comment]
I can't reproduce the issue. Please provide more information.

**Comment by tehKapa** [comment]
I'm just trying to install mailhog using this command: `helm install --name mailhog --namespace mailhog  stable/mailhog -f values.yml` 

This is my values file

```yaml
image:
  repository: mailhog/mailhog
  tag: v1.0.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port:
    http: 8025
    smtp: 2525
  nodePort:
    http: ""
    smtp: ""

securityContext:
  runAsUser: 1000
  fsGroup: 1000
  runAsNonRoot: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: mailhog.mydomain.com
      paths: ["/"]

   tls:
     - hosts:
         - mailhog.mydomain.com
       secretName: mailhog-tls

auth:
  enabled: false
  existingSecret: ""
  fileName: auth.txt
  fileContents: ""

podAnnotations: {}

extraEnv: []
#   - name: MH_UI_WEB_PATH
#     value:
#   - name: MH_CORS_ORIGIN
#     value:
#   - name: MH_HOSTNAME
#     value:
#   - name: MH_API_BIND_ADDR
#     value:
#   - name: MH_UI_BIND_ADDR
#     value:
#   - name: MH_MAILDIR_PATH
#     value:
#   - name: MH_MONGO_COLLECTION
#     value:
#   - name: MH_MONGO_DB
#     value:
#   - name: MH_MONGO_URI
#     value:
#   - name: MH_SMTP_BIND_ADDR
#     value:
#   - name: MH_STORAGE
#     value:
#   - name: MH_OUTGOING_SMTP
#     value:
#   - name: MH_AUTH_FILE
#     value:

resources: {}
affinity: {}
nodeSelector: {}
tolerations: []
```

**Comment by unguiculus** [comment]
Using this file, I get the following error because it is not indented correctly:

`Error: failed to parse _scratch/mailhog.yaml: error converting YAML to JSON: yaml: line 36: did not find expected key`

Fixing indentation, the chart installs successfully and the ingress is created.

BTW, your own values file should only contain things you want to change from the default one. It doesn't make sense to copy everything.

**Comment by tehKapa** [comment]
Yep, I know. For debugging reasons I thought of copying the complete file to show what I had touched. But maybe that wasn't a good idea. 

The problem is definitely there of the Ingress, I just don't understand where is the wrong indentation

**Comment by tehKapa** [comment]
Ok, just specify the following vars

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - mailhog.hubme.in
```
