### ISSUE TITLE
Nginx ingress returning 404 on clients or returning default backend

### ISSUE THREAD

**Issue by GieForce** [codecentric/helm-charts#143]
Hi All,

I'm currently facing an issue with the keycloak implementation on Kubernetes. 
I've configured the charts.yaml as shown beneath. However nginx is returning `default backend - 404` on the admin panel and clients. When I change the path to `"/"` the admin panel works but on the clients nginx is returning a `404 - Not Found`. What am I doing possibly wrong? Am I missing some nginx related headers or what?

```
keycloak:
    ingress:
        enabled: true
        path: "/*"
        hosts:
            - somehost.nl
        annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            ingress.kubernetes.io/affinity: cookie
        tls:
        - secretName: some-tls
          hosts:
          - somehost.nl
    extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true" 
```
