### ISSUE TITLE
Keycloak login failure when replicas > 1

### ISSUE THREAD

**Issue by oridool** [codecentric/helm-charts#149]
When I set keycloak.replicas > 1, I cannot login to web console. 
After clicking the username/password, it redirects again to the login screen.
In logs, there is the following error:

16:34:16,486 WARN  [org.keycloak.events] (default task-2) type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=194.90.225.116, error=invalid_code

I managed to **solve** the issue by enable cookie stickiness in the ngnix and set in Values.yaml:
ingress.annotations.nginx.ingress.kubernetes.io/affinity: "cookie"

1) I suggest that in the readme.md file, you'll add this note. Whenever replicas is set to value greater than 1, you need also to enable cookie affinity in ingress.
2) not sure it is an issue, but the original chart key was "annotations.nginx.ingress.kubernetes.io/affinity", while I had to add the "ngnix" prefix: "ngnix.annotations.nginx.ingress.kubernetes.io/affinity.

**Comment by campenberger** [comment]
I have the problem. replicas is set to 2, but the jgroup variables are not configured in the generated statefulset:
```
# Source: keycloak/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-cc
  labels:
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-6.0.3
    app.kubernetes.io/instance: keycloak-cc
    app.kubernetes.io/managed-by: Tiller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: keycloak-cc
  replicas: 2
  serviceName: keycloak-cc-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/instance: keycloak-cc
      annotations:
        checksum/config-sh: c79822799f71bdd2ded30ba4f74a0eaf5a900df6652ea919c9defda8524dc997
        checksum/config-startup: 77507a988c74ee0186ccdd21bb7bc28999a2854e571891655d68435214912b70
    spec:
      restartPolicy: Always
      serviceAccountName: default
      securityContext:
        fsGroup: 1000
        
      containers:
        - name: keycloak
          image: "jboss/keycloak:7.0.1"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            
          command:
            - /scripts/keycloak.sh
          lifecycle:
            # postStart:
            #   exec:
            #     command: ["/bin/sh", "-c", "ls"]
            
          env:
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD_FILE
              value: /secrets/password
            
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              value: "pgsql"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-pgsql
                  key: "password"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            # - name: KEYCLOAK_LOGLEVEL
            #   value: DEBUG
            # - name: WILDFLY_LOGLEVEL
            #   value: DEBUG
            # - name: CACHE_OWNERS
            #   value: "2"
```
The JGROUPS_ variables should be right after the KEYCLOAD_PASSWORD_FILE
