### ISSUE TITLE
[keycloak] helm3 tpl not expanding template

### ISSUE THREAD

**Issue by Rjvs** [codecentric/helm-charts#151]
Using Helm 3.0 & 3.0.1, the tpl instruction doesn't appear to be expanding the template text, so the output looks like:

```
keycloak:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "keycloak.selectorLabels" . | nindent 10 }}
            matchExpressions:
 ```
