### ISSUE TITLE
Importing realm with script upload disabled since keycloak 7

### ISSUE THREAD

**Issue by donders** [codecentric/helm-charts#163]
as described in https://keycloak.discourse.group/t/cant-import-realm-using-docker-image/259/5

using the method described in the README for importing a realm, I get the following warning:

`16:51:04,392 WARN  [org.keycloak.services] (ServerService Thread Pool -- 68) KC-SERVICES0005: Unable to import realm quarkus from file /realm/realm.json.: java.lang.RuntimeException: Script upload is disabled    `

It would be nice if the mechanism for realm import could be updated.

**Comment by unimosil** [comment]
Add this to your extraArgs: -Dkeycloak.profile.feature.upload_scripts=enabled
Keycloak will still say the function is deprecated, but it sure works.

**Comment by unimosil** [comment]
`kubectl create secret -n keycloak generic realm-secret --from-file=<filename>.json`

`keycloak:
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret
  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/realm/"
      readOnly: true
  extraArgs: "-Dkeycloak.import=/realm/<filename>.json -Dkeycloak.migration.realmName=<realm> -Dkeycloak.profile.feature.upload_scripts=enabled"`

**Comment by oscarlofwenhamn** [comment]
Is this the only way of doing it? Since [script uploading is deprecated](https://www.keycloak.org/docs/latest/server_installation/#profiles) and will be removed in future versions, this needs to be fixed in that case.

**Comment by unimosil** [comment]
I'm not sure. Btw you might need to downgrade appversion to make it work. Then upgrade keycloak again. 
Hoping to find another way to do this..

**Comment by amu007** [comment]
i'm worked this out with no downgrade.
u can have a try

containers:
- name: keycloak
  image: hub.kce.ksyun.com/autodl/keycloak:11.0.2
  imagePullPolicy: Always
  env:
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: KEYCLOAK_PASSWORD
    - name: DB_VENDOR
      value: mysql
    - name: DB_ADDR
      value: mysql_url
    - name: DB_PORT
      value: "mysql_port"
    - name: DB_USER
      value: mysql_user
    - name: DB_PASSWORD
      value: mysql_password
    - name: DB_DATABASE
      value: keycloak
    - name: KEYCLOAK_IMPORT
      value: "/data/test-realm-config/test-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"

**Comment by amu007** [comment]
i'm worked this out with no downgrade. 
u can have a try

```
containers:
- name: keycloak
  image: hub.kce.ksyun.com/autodl/keycloak:11.0.2
  imagePullPolicy: Always
  env:
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: KEYCLOAK_PASSWORD
    - name: DB_VENDOR
      value: mysql
    - name: DB_ADDR
      value: mysql_url
    - name: DB_PORT
      value: "mysql_port"
    - name: DB_USER
      value: mysql_user
    - name: DB_PASSWORD
      value: mysql_password
    - name: DB_DATABASE
      value: keycloak
    - name: KEYCLOAK_IMPORT
      value: "/data/test-realm-config/test-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
```
