### ISSUE TITLE
dns_query is correct but still "does not matchg own cookie"

### ISSUE THREAD

**Issue by zeph** [codecentric/helm-charts#166]
ideas? case this is getting pretty frustrating... the `headless` fqdn which is passed to the probe and to the `KEYCLOAK_SERVICE_DNS_NAME` (what for?) work properly... so, where's the error?

```keycloak 13:10:18,041 WARN  [org.jgroups.protocols.TCP] (TcpServer.Acceptor[7600]-2,null,null) JGRP000006: failed accepting connection from peer: java.net.SocketException: 172.31.97.75:7600: BaseServer.TcpConnection.readPeerAddress(): cookie sent by /172.31.94.101:49632 does not match own cookie; terminating connection
keycloak-1 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpConnection.readPeerAddress(TcpConnection.java:247)
keycloak-1 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpConnection.<init>(TcpConnection.java:53)
keycloak-1 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpServer$Acceptor.handleAccept(TcpServer.java:126)
keycloak-1 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpServer$Acceptor.run(TcpServer.java:111)
keycloak-1 keycloak 	at org.jboss.as.clustering.jgroups@18.0.1.Final//org.jboss.as.clustering.jgroups.ClassLoaderThreadFactory.lambda$newThread$0(ClassLoaderThreadFactory.java:52)
keycloak-1 keycloak 	at java.base/java.lang.Thread.run(Thread.java:834)
keycloak-1 keycloak 
keycloak-2 keycloak 	at java.base/java.lang.Thread.run(Thread.java:834)
keycloak-2 keycloak 
keycloak-2 keycloak 13:10:20,412 WARN  [org.jgroups.protocols.TCP] (TcpServer.Acceptor[7600]-2,null,null) JGRP000006: failed accepting connection from peer: java.net.SocketException: 172.31.86.94:7600: BaseServer.TcpConnection.readPeerAddress(): cookie sent by /172.31.110.0:35026 does not match own cookie; terminating connection
keycloak-2 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpConnection.readPeerAddress(TcpConnection.java:247)
keycloak-2 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpConnection.<init>(TcpConnection.java:53)
keycloak-2 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpServer$Acceptor.handleAccept(TcpServer.java:126)
keycloak-2 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpServer$Acceptor.run(TcpServer.java:111)
keycloak-2 keycloak 	at org.jboss.as.clustering.jgroups@18.0.1.Final//org.jboss.as.clustering.jgroups.ClassLoaderThreadFactory.lambda$newThread$0(ClassLoaderThreadFactory.java:52)
keycloak-2 keycloak 	at java.base/java.lang.Thread.run(Thread.java:834)
keycloak-2 keycloak 
keycloak-0 keycloak 13:10:22,497 WARN  [org.jgroups.protocols.TCP] (TcpServer.Acceptor[7600]-2,null,null) JGRP000006: failed accepting connection from peer: java.net.SocketException: 172.31.94.93:7600: BaseServer.TcpConnection.readPeerAddress(): cookie sent by /172.31.94.101:47074 does not match own cookie; terminating connection
keycloak-0 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpConnection.readPeerAddress(TcpConnection.java:247)
keycloak-0 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpConnection.<init>(TcpConnection.java:53)
keycloak-0 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpServer$Acceptor.handleAccept(TcpServer.java:126)
keycloak-0 keycloak 	at org.jgroups@4.1.4.Final//org.jgroups.blocks.cs.TcpServer$Acceptor.run(TcpServer.java:111)
keycloak-0 keycloak 	at org.jboss.as.clustering.jgroups@18.0.1.Final//org.jboss.as.clustering.jgroups.ClassLoaderThreadFactory.lambda$newThread$0(ClassLoaderThreadFactory.java:52)
keycloak-0 keycloak 	at java.base/java.lang.Thread.run(Thread.java:834)
````

here is my `vaules.yaml` with a couples of extra templates to have the `sealedsecrets` I need

```yaml

$ cat values-XXX.yaml 
nameOverride: "XXX"
keycloak:
  sealedPassword: 'XXX'
  persistence:
    sealedPassword: 'XXX'
  federation:
    sealedKeytab: 'XXX'
  # here come the overrides for the "codecentic" maintained helm chart
  keycloak:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/auth/realms/XXX/metrics"
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi
    replicas: 3
    ingress:
      enabled: true
      hosts:
        - 'XXX'
    extraEnv: |
      - name: KEYCLOAK_HOSTNAME
        value: "XXX"
      - name: KEYCLOAK_HTTP_PORT
        value: "80"
      - name: KEYCLOAK_HTTPS_PORT
        value: "443"
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
    # Admin UI access
    username: admin
    existingSecret: 'keycloak-XXX-http'
    existingSecretKey: 'password'
    # Database stuff
    persistence:
      deployPostgres: false
      dbVendor: 'postgres'
      dbName: 'XXX-keycloak'
      dbHost: 'db01.XXX:5432,db02.XXX:5432,db03.XXX:5432'
      dbUser: 'XXX-keycloak'
      existingSecret: 'keycloak-XXX-db'
      existingSecretKey: 'password'
    extraVolumeMounts: |
      - name: providers
        mountPath: /opt/jboss/keycloak/providers
    extraVolumes: |
      - name: providers
        configMap:
          defaultMode: 365
          name: keycloak-metrics-spi.jar
      - name: kerberos
        secret:
          defaultMode: 420
          items:
          - key: HTTP_keycloak.keytab
            path: krb5.keytab
          secretName: keycloak-XXX-keytab
```
