### ISSUE TITLE
Keycloak: initial user is not set up.

### ISSUE THREAD

**Issue by aperullo** [codecentric/helm-charts#169]
Using the setting for existing secret doesn't load that user in the latest chart version. This previously worked in version 4.14

```
keycloak:
  existingSecret: keycloak-password

  extraArgs: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/import.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
  persistence:
    deployPostgres: true
    dbVendor: postgres

  ingress:
    enabled: true

  # Mount the import file
  extraVolumes: |
    - name: import-vol
      configMap:
        name: auth-import
        defaultMode: 365 
  extraVolumeMounts: |
    - name: import-vol
      mountPath: /opt/jboss/import.json
      subPath: import.json

postgresql:
  postgresqlUser: "keycloak"
  persistence:
    enabled: true
  volumePermissions:
    enabled: true
```

Results in 

```
You need local access to create the initial admin user.

Open http://localhost:8080/auth
or use the add-user-keycloak script.
```

![image](https://user-images.githubusercontent.com/18688190/73788159-87e10d00-476a-11ea-9b5e-9296024ceca0.png)

**Comment by PiePra** [comment]
A solution that worked for me was to provide the user and password with extraEnv:
``` yaml
# Additional environment variables for Keycloak
extraEnv: |
  - name: KEYCLOAK_USER
    value: <user>
  - name: KEYCLOAK_PASSWORD
    value: <password>
```

**Comment by unguiculus** [comment]
Closing as solved. See also https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#creating-a-keycloak-admin-user

**Comment by Edorka** [comment]
Sorry but this is not a solid solution as it keeps username and password plain on the StatefulSet.

A correct solution implies creating a proper secrets

**Comment by KetulRadadiya** [comment]
@Edorka For me it's working only when I set as below :

```
extraEnv: |
  - name: KEYCLOAK_USER
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-settings
        key: admin-username
  - name: KEYCLOAK_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-settings
        key: admin-password

postgresql:
  enabled: false
```

But in same config block when I enable postgres dependency then keycloak pod gets ```CrashLoopBackOff````.
