### ISSUE TITLE
Unable to login as keycloak user

### ISSUE THREAD

**Issue by iirekm** [codecentric/helm-charts#174]
values.yaml:
```
keycloak:
  fullnameOverride: keycloak
  #existingSecret: keycloak # also doesn't work
  password: keycloak123
```

URL: http://10.43.235.116/ (from kubernetes Service)
logs:
```
08:39:58,576 WARN  [org.keycloak.events] (default task-3) type=LOGIN_ERROR, realmId=master, clientId=security-admin-console, userId=26c358fa-c96e-4cf1-99b7-3da4878a39ae, ipAddress=10.42.0.1, error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, redirect_uri=http://10.43.235.116/auth/admin/master/console/, code_id=51431bc8-b9fc-4b5a-b197-104ed3f7b493, username=keycloak, authSessionParentId=51431bc8-b9fc-4b5a-b197-104ed3f7b493, authSessionTabId=1OrSBOUf3N8
```

Please fix it, or provide a better explanation in README how to use this chart.

**Comment by iirekm** [comment]
It's because this chart uses very confusing naming conventions!

If I include it inside another chart, values.yaml must look like:
```yaml
keycloak:
  fullnameOverride: keycloak
  keycloak:
     existingSecret: keycloak
```

Why some settings are inside 'keycloak' and some not?
