### ISSUE TITLE
[Keycloak] keycloak.startupScripts expects an object, not an array

### ISSUE THREAD

**Issue by adelisle** [codecentric/helm-charts#180]
Contrary to the documentation provided, the key `keycloak.startupScripts` does not expect an array (`[]`) as specified but rather an object (`{}`) as found from the CI tests.

**Comment by adelisle** [comment]
Still related to documentation: `keycloak.extraEnv`'s default value isn't `""` but rather:
```yaml
keycloak.extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
```
