### ISSUE TITLE
keycloak connect mysql error

### ISSUE THREAD

**Issue by zznnqq210** [codecentric/helm-charts#182]
When I install keycloak connected an exists mysql:5.7.23 instance  , I see an error `javax.net.ssl.SSLHandshakeException: No appropriate protocol(protocol is disabled or cipher suites are inappropriate)`.
My charts config is that:
```
keycloak:
  image:
    tag: 9.0.0
  ingress:
    enabled: true
    hosts:
     - keycloak.example.com
  username: admin
  password: admin
  replicas: 3
  persistence:
    dbVendor: mysql
    dbName: keycloak
    dbHost: mysql
    dbPort: 3306
    dbUser: root
    dbPassword: root
```
Why this happens?

**Comment by ivangfr** [comment]
Hi @zznnqq210 one way I've found to solve this problem was by appending this
```
keycloak:
  extraEnv: |
    - name: JDBC_PARAMS
      value: useSSL=false
```
I hope it helps!

**Comment by ashish235** [comment]
@ivangfr I was also having the same issue. Your solution helped it works now, thanks. However when I am trying to add users, I am getting deadlocks. The same thing is working with postgres. If you can please help. 

> 20:14:01,227 INFO  [org.keycloak.events] (default task-6) type=LOGIN, realmId=master, clientId=admin-cli, userId=0a59fa8c-45a8-432f-98d7-748348e53934, ipAddress=10.244.2.79, auth_method=openid-connect, token_id=241cda27-cec5-492f-85bb-71ca53276131, grant_type=password, refresh_token_type=Refresh, scope='email profile', refresh_token_id=ac386413-8cb5-43be-b03c-380ac3ac9506, client_auth_method=client-secret, username=admin
20:14:01,301 INFO  [org.keycloak.events] (default task-6) operationType=CREATE, realmId=master, clientId=e30fc3fd-58f1-4cdb-a7db-e1f86b5dd92e, userId=0a59fa8c-45a8-432f-98d7-748348e53934, ipAddress=10.244.2.79, resourcePath=/test/clients/9935e747-bcf7-44c9-99e3-e7d7a584e6d7
20:14:01,432 INFO  [org.keycloak.events] (default task-6) operationType=CREATE, realmId=master, clientId=e30fc3fd-58f1-4cdb-a7db-e1f86b5dd92e, userId=0a59fa8c-45a8-432f-98d7-748348e53934, ipAddress=10.244.2.79, resourcePath=/test/clients/9935e747-bcf7-44c9-99e3-e7d7a584e6d7
20:14:01,626 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-7) SQL Error: 1213, SQLState: 40001
20:14:01,626 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-7) Deadlock found when trying to get lock; try restarting transaction
20:14:01,631 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-6) SQL Error: 1213, SQLState: 40001
20:14:01,634 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-6) Deadlock found when trying to get lock; try restarting transaction
20:14:01,638 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-9) SQL Error: 1213, SQLState: 40001
20:14:01,638 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-9) Deadlock found when trying to get lock; try restarting transaction

**Comment by ivangfr** [comment]
Hey @ashish235 I will try to reproduce it locally using Minikube and I let you know. Btw, what is the Keycloak version you are using?

**Comment by ashish235** [comment]
@ivangfr thanks for responding. I am using keycloak version 5.0.0 and 4.8.final. With both the versions I have this issue. 
There is however one thing you should know. I was using a 3rd party application with this keycloak, and it came with a seed data file in java (unfortunately I can't share that as it's I don't have the source code or anything), which upon start for the 1st time, calls some keycloak apis to create some users, groups etc. When this seed data runs, I am getting this error from keycloak with mysql backend. The same seed data works with h2 and postgres. When I do actions from the UI with mysql backend everything seems to be working. 

So I really don't know the issue here is mysql or keycloak with mysql. I am btw using mysql helm chart with lastest image tag.

**Comment by akkie** [comment]
There exists an [issue for Keycloak](https://issues.redhat.com/browse/KEYCLOAK-11988) which suggest to add `&enabledTLSProtocols=TLSv1.2` to the connection string. The helm template doesn't allow to add something to the JDBC connection string. So I have no idea how this could be added. Any suggestions?

**Comment by ivangfr** [comment]
Hey @akkie 

Using something like
```
keycloak:
  extraEnv: |
    - name: JDBC_PARAMS
      value: useSSL=false&enabledTLSProtocols=TLSv1.2
```

Doesn't work?

I saw the Keycloak issue that you shared and I tried to reproduce it locally using a pet-project that I have (https://github.com/ivangfr/kubernetes-environment), but I didn't get any error.

Could you also share the Keycloak and MySQL version that you are using?

**Comment by akkie** [comment]
@ivangfr 

Thanks for the hint 👍 

```yaml
keycloak:
  extraEnv: |
    - name: JDBC_PARAMS
      value: enabledTLSProtocols=TLSv1.2
```

works!

We use AWS Aurora Serverless.
