### ISSUE TITLE
keycloak.persistence.existingSecretUsernameKey seems to be set to `username` whatever happens

### ISSUE THREAD

**Issue by zadigus** [codecentric/helm-charts#191]
I am trying to install the keycloak chart with the following configuration:
```
- name: keycloak
  helm:
    chart:
      name: keycloak
      repo: https://codecentric.github.io/helm-charts
    values:
      clusterDomain: ${CLUSTER_DOMAIN}
      keycloak:
        image:
          tag: 9.0.0
        username: admin
        password: admin
        persistence:
          deployPostgres: false
          existingSecret: postgres-postgresql
          existingSecretPasswordKey: postgresql-password
          existingSecretUsernameKey: ""
          dbVendor: postgres
          dbName: keycloak
          dbHost: postgres-pgpool
          dbPort: 5432
          dbUser: postgres
```
I want to use a postgresql instance that already exists on my cluster and which defines a secret, in which I only have the database password, but not the database username (that's how [bitnami's chart](https://hub.helm.sh/charts/bitnami/postgresql-ha) works). In your documentation, you state
```
keycloak.persistence.existingSecretUsernameKey: The key for the database username in the existing secret (if keycloak.persistence.deployPostgres=false and keycloak.persistence.existingSecret != ""). Will default to the value of .keycloak.persistence.dbUser if left unset.
```
Therefore, in my config, I set
```
existingSecretUsernameKey: ""
```
making it "left unset". Therefore, I expect the `dbUser` value to be used as the username. Upon installation, I get the following error message:
```
Error: Couldn't find key username in Secret dev/postgres-postgresql
```
What do I have to do to let this helm installation use the `dbUser` I want with my existing password?

**Comment by zadigus** [comment]
Ok. I see now two solutions to this problem: 

1. your chart seems to assume that it's either I have a secret file or I don't; if I have one, then it **must** contain both the password and the username (cf. [this code](https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/templates/_helpers.tpl#L178)):
```
- name: DB_USER
  valueFrom:
    secretKeyRef:
      name: {{ include "keycloak.dbSecretName" . }}
      key: {{ include "keycloak.dbUserKey" . | quote }}
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: {{ include "keycloak.dbSecretName" . }}
      key: {{ include "keycloak.dbPasswordKey" . | quote }}
```
This code could be generailized in such a way that it could use the password from a secret and the username from the values provided as arguments to the helm installation.

2. I can create my own secret holding both the password and username and so that the secret file complies to both the postgresql-ha and keycloak helm charts. I will go for that one as it will be faster for me.
