### ISSUE TITLE
Ingress ssl-redirect

### ISSUE THREAD

**Issue by Joni-Aaltonen** [codecentric/helm-charts#204]
Nice work! 
Could you consider adding in support for alb-ingress-controller type tls-redirect?

https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/

**Comment by rohitmahajan29** [comment]
do you this yaml file for google cloud?

**Comment by unguiculus** [comment]
The chart already allows you to add custom annotations to the ingress like so:

```yaml
keycloak:
  ingress:
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:xxxx:certificate/xxxxxx
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
```
