### ISSUE TITLE
[keycloak 9.0.2] mysql  Error: Row size too large

### ISSUE THREAD

**Issue by luolizhi** [codecentric/helm-charts#213]
Environment

mysql version : 5.7.29

i create secret manual before run  the charts, and there are tables created in my database.

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", B
uildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", B
uildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

charts values
```
keycloak:
  extraEnv: |
    - name: JDBC_PARAMS
      value: useSSL=false
  persistence:
 
    # The database vendor. Can be either "postgres", "mysql", "mariadb", or "h2"
    dbVendor: mysql

    ## The following values only apply if "deployPostgres" is set to "false"
    dbName: keycloak
    dbHost: 192.168.1.1
    dbPort: 3306

    ## Database Credentials are loaded from a Secret residing in the same Namespace as keycloak.
    ## The Chart can read credentials from an existing Secret OR it can provision its own Secret.

    ## Specify existing Secret
    # If set, specifies the Name of an existing Secret to read db credentials from.
    existingSecret: "secret-db"
    existingSecretPasswordKey: "password"  # read keycloak db password from existingSecret under this Key
    existingSecretUsernameKey: "username" 
```

the error log:
```
02:28:49,507 ERROR [org.keycloak.connections.jpa.updater.liquibase.conn.DefaultLiquibaseConnectionProvider] (ServerService Thread Pool -- 66) Change Se
t META-INF/jpa-changelog-1.9.1.xml::1.9.1::keycloak failed.  Error: Row size too large. The maximum row size for the used table type, not counting BLOB
s, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs [Failed SQL: ALTER TABLE keycloak.REALM
 MODIFY CERTIFICATE VARCHAR(4000)]
02:28:49,514 FATAL [org.keycloak.services] (ServerService Thread Pool -- 66) java.lang.RuntimeException: Failed to update database

02:28:49,786 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "microprofile-metrics-smallrye")]): java.lang.NullPointerException
	at org.wildfly.extension.microprofile.metrics-smallrye@18.0.1.Final//org.wildfly.extension.microprofile.metrics.MicroProfileMetricsSubsystemAdd$2.ex
ecute(MicroProfileMetricsSubsystemAdd.java:86)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:999)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:743)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:467)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1413)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:521)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:472)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:434)
	at org.jboss.as.server@10.0.3.Final//org.jboss.as.server.ServerService.boot(ServerService.java:435)
	at org.jboss.as.server@10.0.3.Final//org.jboss.as.server.ServerService.boot(ServerService.java:394)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:374)
	at java.base/java.lang.Thread.run(Thread.java:834)

02:28:49,791 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0190: Step handler org.jboss.as.server.DeployerChainA
ddHandler$FinalRuntimeStepHandler@383ca6ea for operation add-deployer-chains at address [] failed handling operation rollback -- java.util.concurrent.R
ejectedExecutionException: java.util.concurrent.RejectedExecutionException
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:37)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2026)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:757)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.notification.NotificationSupports$NonBlockingNotificationSupport.emit(NotificationS
upports.java:95)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.OperationContextImpl.notifyModificationBegun(OperationContextImpl.java:877)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.OperationContextImpl.ensureWriteLockForRuntime(OperationContextImpl.java:866)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.OperationContextImpl.removeService(OperationContextImpl.java:639)
	at org.jboss.as.server@10.0.3.Final//org.jboss.as.server.DeployerChainAddHandler$FinalRuntimeStepHandler$1.handleRollback(DeployerChainAddHandler.java:135)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.AbstractOperationContext$RollbackDelegatingResultHandler.handleResult(AbstractOperationContext.java:1561)
	at org.jboss.as.controller@10.0.3.Final//org.jboss.as.controller.AbstractOperationContext$Step.invokeResultHandler(AbstractOperationContext.java:1533)
```

i can't find where the sql execute, how can  fix this fail, Any suggestions will be help, thanks in advance!
