### ISSUE TITLE
 Destination for readinessProbe is a table, wrong type for value; expected string; got map[string]interface {}

### ISSUE THREAD

**Issue by hristo-yordanov** [codecentric/helm-charts#222]
Hi,
I'm trying to deploy the latest chart version on minikube, but I'm getting:

> helm install keycloak codecentric/keycloak --values keycloak-local.yaml

```coalesce.go:199: warning: destination for readinessProbe is a table. Ignoring non-table value httpGet:
  path: {{ if ne .Values.keycloak.basepath "" }}/{{ .Values.keycloak.basepath }}{{ end }}/realms/master
  port: http
initialDelaySeconds: 30
timeoutSeconds: 1
coalesce.go:199: warning: destination for readinessProbe is a table. Ignoring non-table value httpGet:
  path: {{ if ne .Values.keycloak.basepath "" }}/{{ .Values.keycloak.basepath }}{{ end }}/realms/master
  port: http
initialDelaySeconds: 30
timeoutSeconds: 1
Error: template: keycloak/templates/statefulset.yaml:153:20: executing "keycloak/templates/statefulset.yaml" at <.>: wrong type for value; expected string; got map[string]interface {}
```

the content of keycloak-local.yaml is:

```
init:
 image:
  pullPolicy: Always

keycloak:
 username: admin
 password: admin
 readinessProbe:
  timeoutSeconds: 60
 service:
  type: NodePort
 persistence:
  deployPostgres: true
  dbVendor: postgres
 ingress:
  enabled: true
  hosts:
   - localhost
 extraEnv: |
   - name: PROXY_ADDRESS_FORWARDING
     value: "true"
```
