### ISSUE TITLE
stuck with redirect to /auth

### ISSUE THREAD

**Issue by pixie79** [codecentric/helm-charts#225]
Hi,

I have setup my keycloak instance using an AWS ALB. I am struggling at the moment to get it to connect. If I port forward to the service  "kubectl port-forward service/keycloak-http 8080:8080" then I can login ok to keycloak.

However if i try and hit my url e.g http://keycloak.example.com it redirects to http://keycloak.example.com/auth and then seems to stop, without giving me the login screen. Any ideas what I have done wrong?

Ideally I would like http disabled or a redirect to https as well.

## service.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-7.5.0
    service: http
  name: keycloak-http
  namespace: default
spec:
  clusterIP: 172.XX.XX.25
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31322
    port: 8080
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31849
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

## ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:XXXX:certificate/XXXX
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":8080,"HTTPS": 8443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-7.5.0
  name: keycloak
  namespace: default
spec:
  rules:
  - host: keycloak.example.com
    http:
      paths:
      - backend:
          serviceName: keycloak-http
          servicePort: http
        path: /
status:
  loadBalancer:
    ingress:
    - hostname: XXXX-default-keycloak-XXXX.eu-west-2.elb.amazonaws.com
```

## statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: keycloak-7.5.0
  name: keycloak
  namespace: default
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
  serviceName: keycloak-headless
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: keycloak
        app.kubernetes.io/name: keycloak
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: role
                  operator: NotIn
                  values:
                  - test
                matchLabels:
                  app.kubernetes.io/instance: keycloak
                  app.kubernetes.io/name: keycloak
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: NotIn
                values:
                - test
              matchLabels:
                app.kubernetes.io/instance: keycloak
                app.kubernetes.io/name: keycloak
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /scripts/keycloak.sh
        env:
        - name: KEYCLOAK_USER
          value: keycloak
        - name: KEYCLOAK_PASSWORD_FILE
          value: /secrets/password
        - name: JAVA_TOOL_OPTIONS
          value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=50.0
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: XXXX.eu-west-2.rds.amazonaws.com
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: XXXX
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: keycloak-db
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-db
        image: jboss/keycloak:9.0.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth/
            port: http
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth/realms/master
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: sh
          readOnly: true
        - mountPath: /secrets
          name: secrets
          readOnly: true
        - mountPath: /opt/jboss/startup-scripts
          name: startup
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 365
          name: keycloak-sh
        name: sh
      - name: secrets
        secret:
          defaultMode: 420
          secretName: keycloak-http
      - configMap:
          defaultMode: 365
          name: keycloak-startup
        name: startup
  updateStrategy:
    type: RollingUpdate
