### ISSUE TITLE
[Jenkins] extra directories in referenceContent.relativeDir

### ISSUE THREAD

**Issue by jorikseldeslachts** [codecentric/helm-charts#230]
Hi all,

I am trying to create a subdirectory in /var/jenkins_home with a file inside that directory. Both the directory and the file get created but there are also two extra directories present in the directory.

I use this in my `values.yaml` file as stated in the docs:
```yaml
referenceContent:
  - relativeDir: testdir
    data:
      - fileName: test.txt
        fileContent: |
          abc def
          123469
          test
```
When I enter the container and go to /var/jenkins_home/testdir, I also see two other directories:
```sh
drwxr-xr-x 2 jenkins jenkins 4096 May 21 12:16 ..2020_05_21_12_12_37.984814017
drwxr-xr-x 2 jenkins jenkins 4096 May 21 12:16 ..data
-rw-r--r-- 1 jenkins jenkins   22 May 21 12:16 test.txt
```

Why are those `..data` and `..2020_05_21_12_12_37.984814017` directories created?

Thanks!
