### ISSUE TITLE
extraEnv defined in helm secrets is overridden by extraEnv defined in helm values

### ISSUE THREAD

**Issue by DeniseSala** [codecentric/helm-charts#238]
I need to specify some secrets that my spi and Keycloak realm use. The only way I found to do that, is to define them as extraEnv. But I can only define once the extraEnv map, or in values or in secrets, and it's unpractical to decrypt every time the secrets to check the configuration. 
I would like to have a separate map for defining secrets (i.e. extraEnvSecrets).

**Comment by unguiculus** [comment]
I'm afraid I don't really understand the problem. Maybe you could share your configs?

**Comment by DeniseSala** [comment]
Hi, yes. 
In my `realm.json` file I have some env specific configurations, like the social id provider settings:
``` json
"identityProviders" : [
    {
      "alias" : "google",
      "internalId" : "94599847-5c50-468b-9515-e56a22b1871f",
      "providerId" : "google",
      "enabled" : true,
      "updateProfileFirstLoginMode" : "on",
...
      "config" : {
        "hideOnLoginPage" : "",
        "clientId" : "$GOOGLE_ID",
        "disableUserInfo" : "false",
        "userIp" : "",
        "clientSecret" : "$GOOGLE_SECRET",
        "defaultScope" : "email profile openid",
        "useJwksUrl" : "true"
      }
    },
``` 
As you can see, I need to inject some env variables here: one for the secret and one for the clientId. 
Ideally I would like to have the GOOGLE_SECRET env var defined in `.helm/secrets/secrets.yaml` and `GOOGLE_ID` env var defined in `.helm/values.yaml`. 

The way to add env variables to the helm chart is via the `extraEnv` map.
So I would like to have this map defined both in `./helm/secrets/secrets.yaml` and in `./helm/values.yaml`. 
``` yaml
#./helm/secrets/secrets.yaml
keycloak: 
  extraEnv: |
    - name: GOOGLE_SECRET
      value: "a_secret"

#./helm/values.yaml
keycloak: 
  extraEnv: |
    - name: GOOGLE_ID
      value: "a_value"
```

But if I define `extraEnv` in both files, the 2 maps are not merged. One overrides the other one. 
So I ended up to defining the `extraEnv` map only in `.helm/secrets/secrets.yaml` with all my env variables: 
``` yaml
#./helm/secrets/secrets.yaml
keycloak: 
  extraEnv: |
    - name: GOOGLE_SECRET
      value: "a_secret"
    - name: GOOGLE_ID
      value: "a_value"
```
This is unpractical because every time I need to check the configuration for a given environment, I have to decrypt `./helm/secrets/secrets.yaml`.

What I propose is to have 2 separate maps: `extraEnvSecrets` and `extraEnv`, so that I can define secrets and variables in separate structures:
``` yaml
#./helm/secrets/secrets.yaml
keycloak: 
  extraEnvSecrets: |
    - name: GOOGLE_SECRET
      value: "a_secret"

#./helm/values.yaml
keycloak: 
  extraEnv: |
    - name: GOOGLE_ID
      value: "a_value"
```
Or maybe is there a better option to fix this issue that I haven't considered yet? 
Thank you :)

**Comment by unguiculus** [comment]
`extraEnv` has to be specified as string because it is templated. That means, contents won't be merged if you spread them across multiple values files. However, since they are templated, you can do the following:

#./helm/values.yaml
```yaml
keycloak: 
  extraEnv: |
    - name: GOOGLE_SECRET
      value: {{ .Values.googleSecret }}
    - name: GOOGLE_ID
      value: "a_value"
```

#./helm/secrets/secrets.yaml
```yaml
googleSecret: "a_secret"
```
