### ISSUE TITLE
keycloak chart and istio

### ISSUE THREAD

**Issue by xeor** [codecentric/helm-charts#24]
Istio is unable to inject it's sidecar, the `securityContext` is defined directly on the statefulSet, overwriting what the sidecar needs to do, ending up giving an error like `iptables v1.6.0: can't initialize iptables table "nat": Permission denied (you must be root)`

This is discussed in https://github.com/istio/old_issues_repo/issues/316

I'm testing out replacing

```
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1000
```

directly on the statefulSet, with

```
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
```

on the containers definition instead.

Will attach a PR on this soon if everything seams to work..
