### ISSUE TITLE
Service monitor is missing namespaceSelector in case keycloak resides in another namespace

### ISSUE THREAD

**Issue by ryanskandal** [codecentric/helm-charts#245]
My keycloak pods reside in a namespace `x` while I set the Prometheus service monitor to install in a namespace called `cattle-prometheus`.  Since the service monitor doesn't have a namespace selector, it is looking for the pods to scrape in the wrong namespace.  The only way I solved this is by overriding the ServiceMonitor.yaml file, and included:

```
namespaceSelector:
    any: true
```
, in the spec section.

Ideally there is a value configuration, where one can set a different namespace to scrape.

The following is my configuration:
```
prometheus:
  operator:
    ## Are you using Prometheus Operator?
    enabled: true

    serviceMonitor:
      ## Optionally set a target namespace in which to deploy serviceMonitor
      namespace: "cattle-prometheus"

      ## Additional labels to add to the ServiceMonitor so it is picked up by the operator.
      ## If using the [Helm Chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) this is the name of the Helm release.
      selector:
        prometheus: prometheus-operator

      ## Interval at which Prometheus scrapes metrics
      interval: 10s

      ## Timeout at which Prometheus timeouts scrape run
      scrapeTimeout: 10s

      ## The path to scrape
      path: /auth/realms/master/metrics
```
