### ISSUE TITLE
Trying to Import custom truststore.jks into Keycloak using initcontainer not working

### ISSUE THREAD

**Issue by tehreverand666** [codecentric/helm-charts#261]
Hello, Not sure if I should be posting this here but wasn't sure where else to post this. We are trying to configure our helm/keycloak installation with a custom truststore.jks.

We built a dockerfile with this truststore built in.

The problem is when the init container launches it doesn't seem to be copying the truststore.jks file over. It creates the directory but the file does not show up and thus our pods continue to crash.

I saw the following posted elsewhere on this site about how someone else got it working and that is what I based my attempt off of. They used the below

extraArgs:  -Djavax.net.ssl.trustStore=/opt/jboss/keycloak/standalone/configuration/cacerts Djavax.net.ssl.trustStorePassword=**CHANGEMEDUMMY**

  ## Additional init containers, e. g. for providing custom themes
  extraInitContainers: |
    - name: test-ca
      image: custom image
      imagePullPolicy: Always
           command:
        - sh
      args:
        - -c
        - |
          echo "Copying test truststore.jks.."
          cp -R truststore.jks /test/
      volumeMounts:
        - name: cacerts
          mountPath: /test

  ## Add additional volumes and mounts, e. g. for custom themes
  extraVolumes: |
    - name: cacerts
      emptyDir: {}
  extraVolumeMounts: |
    - mountPath: /opt/jboss/keycloak/standalone/configuration/cacerts
      subPath: cacerts
      name: cacerts

I can see the mount is created when I open a shell to the pod but it's blank.

Any ideas here?

**Comment by darkdragn** [comment]
This is going to sound kind of stupid since it isn't directly addressing your question about a custom jks, but if you're only using it to add a custom CA there's a part of the entrypoint that will handle that for you if you provide the CA in pem format. Here's how we accomplished that:

```yaml
# The base keycloak image will add the CA's from X509_CA_BUNDLE to the default jks
extraEnvs: |
  - name: X509_CA_BUNDLE
    value: /x509/ca.crt
extraVolumes: |
  - name: x509
    secret:
      defaultMode: 420
      secretName: ca-bundle
extraVolumeMounts:
  - mountPath: /x509
    name: x509
    readOnly: true

```

With that in place, the logs for keycloak report that it loaded the CA's into the default JKS. Our use case is for PKI Auth, and it's working perfectly. I'm not sure if it'll fit your use case though. Let me know how it goes!
