### ISSUE TITLE
[keycloak] how to use other DB like mariadb

### ISSUE THREAD

**Issue by Hokwang** [codecentric/helm-charts#270]
Hello.

I am using your keycloak chart with mariadb,
recently chart has big changes,

and there's nothing comments for several DBs except postgresql.

Can I use mariadb with keycloak? If so, can you comment how to do it?

Thanks,

**Comment by bbelojevic** [comment]
I'm also interested in this.

**Comment by palsch** [comment]
Hello @Hokwang , @bbelojevic ,

you still can use the mariadb with this chart.
This is the documentation for your usecase: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#using-a-secret-managed-by-the-chart

Here are my comments to the code from the documentation:

```
# Disable PostgreSQL dependency
postgresql:
  enabled: false

extraEnv: |
  - name: DB_VENDOR
    value: mariadb
  - name: DB_ADDR
    value: keycloak-mariadb
  - name: DB_PORT
    value: "3306"
  - name: DB_DATABASE
    value: keycloak

# read the given secret and add all the secret data to the environment variables
# in this case we read the secret that is created below and create two environment variables: DB_USER and DB_PASSWORD
extraEnvFrom: |
  - secretRef:
      name: '{{ include "keycloak.fullname" . }}-db'

# create new secret with name: <keycloak.fullname>-db, add DB_USER and DB_PASSWORD to this secret
# name of the secret data should be the same that is used by keycloak from environment variables
# see https://github.com/keycloak/keycloak-containers/blob/11.0.0/server/README.md#environment-variables
secrets:
  db:
    stringData:
      DB_USER: '{{ .Values.dbUser }}'
      DB_PASSWORD: '{{ .Values.dbPassword }}'

```

Best regards
Paul
