### ISSUE TITLE
Cannot configure extraenv

### ISSUE THREAD

**Issue by CalamarBicefalo** [codecentric/helm-charts#274]
Helm Chart version: 9.0.1

When I try to apply the config as per the docs:
```yaml
keycloak:
  replicas: 1
  extraEnv:
    - name: PROXY_ADDRESS_FORWARDING
      value: true
```

I also tried:

```yaml
keycloak:
  replicas: 1
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: true
```

In both cases I get:
`- extraEnv: Invalid type. Expected: string, given: object`

If I remove extraEnv it works just fine and the replicas are picked as specified. How should I configure extraEnv?
