### ISSUE TITLE
Default service.httpPort in 9.0.1 should be 8080 not 80

### ISSUE THREAD

**Issue by damianjaniszewski** [codecentric/helm-charts#284]
In 9.0.1 default value for service.httpPort is 80 while keycloak server actually listens on 8080. Both keycloak-http and keycloak-headless services affected.

**Comment by unguiculus** [comment]
You're confusing container port with service port. The container port is indeed 8080, whereas 80 has always been used by this chart for the service port. This has not changed in 9.0.1. You can reconfigure the service port to your liking.

**Comment by damianjaniszewski** [comment]
Just want to confirm, in service-http.yaml template I can see:
```
ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      {{- if and (eq "NodePort" .Values.service.type) .Values.service.httpNodePort }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
      protocol: TCP
```
To me it looks like both service port and target container port are set to to the same .Values.service.httpPort value because they share same port name? So if default value for service.httpPort is 80 the service targets port 80 on the actual Keycloak container?
