### ISSUE TITLE
keycloak - Error: StatefulSet in version "v1" cannot be handled as a StatefulSet

### ISSUE THREAD

**Issue by voipas** [codecentric/helm-charts#287]
Hi there,

I'm trying to deploy Keycloak with external Postgresql db, but it fails with the following error:

```
keycloak $ helm install keycloak codecentric/keycloak  --namespace security --values keycloak.values.yml --debug
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/pi/.cache/helm/repository/keycloak-9.0.1.tgz

client.go:108: [debug] creating 6 resource(s)
Error: StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 5, error found in #10 byte of ...|,"value":5432},{"nam|..., bigger context ...|ostgresql-postgresql"},{"name":"DB_PORT","value":5432},{"name":"DB_DATABASE","value":"keycloak"},{"n|...
helm.go:94: [debug] StatefulSet in version "v1" cannot be handled as a StatefulSet: v1.StatefulSet.Spec: v1.StatefulSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 5, error found in #10 byte of ...|,"value":5432},{"nam|..., bigger context ...|ostgresql-postgresql"},{"name":"DB_PORT","value":5432},{"name":"DB_DATABASE","value":"keycloak"},{"n|...

```

**Get Pods**
```
keycloak $ kubectl get pods -n security
NAME                      READY   STATUS    RESTARTS   AGE
postgresql-postgresql-0   1/1     Running   0          56m
```

**My configuration of External PostgreSQL**

```
postgresql:
  # If `true`, the Postgresql dependency is enabled
  enabled: false

extraEnv: |
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: postgresql-postgresql
  - name: DB_PORT
    value: 5432
  - name: DB_DATABASE
    value: keycloak
  - name: DB_USER
    value: keycloak
  - name: DB_PASSWORD
    value: keycloak
```

Could you please help me to resolve this issue?
Thanks
