### ISSUE TITLE
Error 404 on "/auth/realms/master/metrics"

### ISSUE THREAD

**Issue by vc43** [codecentric/helm-charts#295]
I want to scrape metrics by Prometheus-operator. I added in my values.yaml:
```
extraEnv: |
  - name: KEYCLOAK_STATISTICS
    value: all
serviceMonitor:
  enabled: true
```
But target is down with error "server returned HTTP status 404 Not Found". Endpoint: http://Pod_IP:8080/auth/realms/master/metrics.
The same error inside pod keycloak-0:
```
bash-4.4$ curl http://127.0.0.1:8080/auth/realms/master/metrics
{"error":"HTTP 404 Not Found"}
```
I also tried http://Pod_IP:8080/metrics.
In the same time http://127.0.0.1:8080/auth/realms/master returns code 200.
