### ISSUE TITLE
postgres.enabled=true does not override extraENV DB_VARS 

### ISSUE THREAD

**Issue by haroonb** [codecentric/helm-charts#308]
Hello I'm running into a issue with my values file.

I have the following values file and if I enable the separate deployment of postgres my statefulset still tries to connect itself to the acid-postgres instance. Is that expected behaviour? I was the expecting the chart to ignore the extraEnv in that case.

```
extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
    # DB-configuration OPS
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: acid-postgres-cluster.default.svc.cluster.local
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: keycloak

postgresql:
  # If `true`, the Postgresql dependency is enabled
  enabled: false
  # PostgreSQL User to create
  postgresqlUsername: keycloak
  # PostgreSQL Password for the new user
  postgresqlPassword: 12345678
  # PostgreSQL Database to create
  postgresqlDatabase: keycloak
  # Persistent Volume Storage configuration

  # PostgreSQL network policy configuration
  networkPolicy:
    enabled: false
```
