### ISSUE TITLE
keycloak not working in minikube with ingress enabled

### ISSUE THREAD

**Issue by dzelge** [codecentric/helm-charts#312]
I attempt to start a keycloak instance with the ingress enabled. I can open the Welcome page. However, when I attempt to loac 
 the administration console I get the following error message:

![image](https://user-images.githubusercontent.com/42441761/94932752-ca114880-04c9-11eb-900a-31933c8074b2.png)

**Comment by darkdragn** [comment]
Hey, @dzelge I got this working on my setup with a little note from the readme on the docker image:

> Enabling proxy address forwarding
When running Keycloak behind a proxy, you will need to enable proxy address forwarding.
docker run -e PROXY_ADDRESS_FORWARDING=true jboss/keycloak

So, adding that to values, it turns out like this:
```yaml
  postgresql:
    enabled: false
  extraEnv: |
    - name: DB_VENDOR
      value: mysql
    - name: DB_ADDR
      value: nextcloud-mariadb.nextcloud.svc
    - name: DB_PORT
      value: "3306"
    - name: DB_NAME
      value: keycloak
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: JAVA_OPTS
      value: >-
        -XX:+UseContainerSupport
        -XX:MaxRAMPercentage=10.0
  extraEnvFrom: |
    - secretRef:
        name: '{{ include "keycloak.fullname" . }}-db'
```
