### ISSUE TITLE
[Keycloak] : Ingress always redirect to /auth using helm charts

### ISSUE THREAD

**Issue by wdesplas** [codecentric/helm-charts#339]
I curently try to use keycloak on AKS with an nginx ingress controler.

I have use the following values.yam: 
```
replicas: 1

ingress:
  # If `true`, an Ingress is created
  enabled: true
  # The Service port targeted by the Ingress
  servicePort: http
  # Ingress annotations
  annotations: 
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  
  path: /auth/?(.*)
  rules:
    -
      # Ingress host
      host: 'keycloak.abs.mydomain.my'
      # Paths for the host
      paths:
        - /
  # TLS configuration
  tls:
    - hosts:
        - keycloak.abs.mydomain.my
      secretName: tls-secret

autoscaling:
  enabled: false

rbac:
  create: true
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs:
        - get
        - list

serviceMonitor:
  # If `true`, a ServiceMonitor resource for the prometheus-operator is created
  enabled: false

extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: keycloak
  - name: KEYCLOAK_STATISTICS
    value: all
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: kubernetes.KUBE_PING
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: CACHE_OWNERS_COUNT
    value: "2"
  - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
    value: "2"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
```

Everything is deploying fine however, once reach the platform, on a browser https://keycloak.abs.mydomain.my/auth, I continiously redirected to /auth.

Could you please help in order to have a fully working example on AKS using nginx ingress controler.

Thanks in advance.
