### ISSUE TITLE
[Keycloak] Invalid ingress specs

### ISSUE THREAD

**Issue by tbnguyen1407** [codecentric/helm-charts#347]
Hello latest helm chart (9.6.0+) includes invalid spec for networking.k8s.io/v1 ingress. This fails when deploying on k8s 1.19+

**Error:**

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
```
**Cause:**

https://github.com/codecentric/helm-charts/blob/8984699ec22d1de39d31919d774bb65c957be8ef/charts/keycloak/templates/ingress.yaml#L36-L41

**Workaround:**

Downgrade to 9.5.0

**Fix:**

for v1 it should be
```
- path: {{ . }}
  pathType: PathPrefix
  backend:
    service:
      name: {{ include "keycloak.fullname" $ }}-http
      port:
        name: {{ $ingress.servicePort }}
```

**Notes:**

You may need to have separate blocks to handle v1 and v1beta1 spec for fallback. Check for exact Ingress resource instead of just networking.k8s.io/v1 since this is also available in older k8s versions

```
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
```
