### ISSUE TITLE
keycloak probes seem to be picked up by postgresql

### ISSUE THREAD

**Issue by esantoro** [codecentric/helm-charts#354]
Hello,
I'm deploying Keycloak using this chart.

I'm enabling the postgresql dependency and using a pvc as a backing store. 

Since I'm setting an empty context path, I'm also using custom readiness and liveness probes.

There is a strange behavior when running `helm upgrade --install` though, as I see the following messages:

```
2020/12/03 13:37:04 Warning: Merging destination map for chart 'postgresql'. Overwriting table item 'readinessProbe', with non table value: httpGet:
  path: "/realms/office/account"
  port: http
initialDelaySeconds: 30
timeoutSeconds: 1
2020/12/03 13:37:04 Warning: Merging destination map for chart 'postgresql'. Overwriting table item 'livenessProbe', with non table value: httpGet:
  path: "/realms/office/account"
  port: http
initialDelaySeconds: 300
timeoutSeconds: 5
```

The release installs just fine however, but I cannot seem to find the source of the problem.

For context, a small extract of my values file:

```
contextPath: ""
livenessProbe: |
  httpGet:
    path: "/realms/office/account"
    port: http
  initialDelaySeconds: 300
  timeoutSeconds: 5

readinessProbe: |
  httpGet:
    path: "/realms/office/account"
    port: http
  initialDelaySeconds: 300
  timeoutSeconds: 1

## DATABASE CONFIGURATION 
postgresql:
  enabled: true
  persistence:
    enabled: true
    existingClaim: postgresql-keycloak
  postgresqlDatabase: keycloak
  postgresqlUsername: keycloak
  existingSecret: keycloak-postgresql
  customLivenessProbe:
    tcpSocket:
      port: 5432
  customReadinessProbe:
    tcpSocket:
      port: 5432
```

I'd like to see the errors about map merges go away as I suspect that leaving this issue unassisted might leat to troubles in the future, do you happend to have any ideas on how to fix this ?
