### ISSUE TITLE
keycloak and cockroachdb cloud

### ISSUE THREAD

**Issue by boraozkan** [codecentric/helm-charts#356]
Hi,

I tried to use keycloak db against crdb cloud. I create a db for the keycloak and give the above configuration to success connection. I use my values.yaml and added additional env var:

```
extraEnv: |
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: xxxx.xxx.cockroachlabs.cloud
  - name: DB_PORT
    value: "xxx"
  - name: DB_DATABASE
    value: keycloak
  - name: DB_USER_FILE
    value: /secrets/db-creds/user
  - name: DB_PASSWORD_FILE
    value:  /secrets/db-creds/password
  - name: JDBC_PARAMS
    value: sslmode=verify-ca&sslrootcert=/secrets/crdb-creds/xxx.crt
  - name: JDBC_PARAMS_FILE
    value: /secrets/crdb-creds/xxx.crt
```
and also 

```
# Add additional volumes, e. g. for custom themes
extraVolumes: |
  - name: crdb-creds
    secret:
      secretName: keycloak-crdb-creds
  - name: db-creds
    secret:
      secretName: keycloak-db-creds
```
and mounting

```
# Add additional volumes mounts, e. g. for custom themes
extraVolumeMounts: |
  - name: crdb-creds
    mountPath: /secrets/crdb-creds
    readOnly: true
  - name: db-creds
    mountPath: /secrets/db-creds
    readOnly: true
```

So in theory there is no restriction for using cockroach the with postgres db vendor in keycloak(!). And I am going to give a try for this and actually it wasn't give an error but it restaring after while and keeping restarting same period. So it gives an :
```
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.sql.SQLException: IJ031040: Connection is not associated with a managed connection: org.jboss.jca.adapters.jdbc.jdk8.WrappedConnectionJDK8@3a612dd6
or
10:55:31,907 FATAL [org.keycloak.services] (ServerService Thread Pool -- 64) Error during startup: java.lang.IllegalStateException: Failed to retrieve lock  
```

So my question is what is the variable for giving .crt path and is there any additional progress need to run this correctly
