### ISSUE TITLE
[keycloak] discovery picks up other clusters

### ISSUE THREAD

**Issue by msvechla** [codecentric/helm-charts#374]
Hello, first of all, thanks a lot for this awesome chart, I appreciate the level of detail and amazing work that has been put into it!

I discovered a potential issue when installing the helm chart multiple times into the same cluster.
When installing the chart two times in the same namespace, I would see logs similar to the following:

```
 Received new cluster view for channel ejb: [cluster1-keycloak-0, cluster2-keycloak-0, ...]
```

We fixed this by modifying the `KUBE_PING` service discovery properties:

```yaml
keycloak:
    properties:
      - labels=>"app.kubernetes.io/instance=cluster1"
``` 

Do you think it would make sense to add this as the default behavior, filtering based on the helm instance label?
I would also be open to help out with a PR if you think this makes sense.

Thanks a lot!

**Comment by unguiculus** [comment]
Thanks for the great feedback.

`KUBE_PING` is not used by default. You will have to configure it yourself anyways, so your suggestion can't be added as a default. We could certainly add it to the respective section in the readme.

How exactly did you configure that? `keycloak.properties` does not exist in the chart. The easist way to achieve what you want would be adding the label as environment variable.

```yaml
extraEnv: |
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: kubernetes.KUBE_PING
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: KUBERNETES_LABELS
    value: 'app.kubernetes.io/instance={{ .Release.Name }}'
```
