### ISSUE TITLE
[keycloak]how to upgrade helm chart to v9? Can't see keycloak master console 

### ISSUE THREAD

**Issue by minkjj** [codecentric/helm-charts#386]
upgraded keycloak helm chart 8.2.2 to 9.9.1
after deploying this value, I can't see master console. 
8.2.2 value 
```yaml
keycloak:
  extraEnv: |
    - name: JDBC_PARAMS
      value: enabledTLSProtocols=TLSv1.2

  extraInitContainers: |
    - name: extensions
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying extensions..."
          wget -O /deployments/keycloak-metrics-spi.jar https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.0.1/keycloak-metrics-spi-2.0.1.jar
      volumeMounts:
        - name: deployments
          mountPath: /deployments
  extraVolumeMounts: |
    - name: deployments
      mountPath: /opt/jboss/keycloak/standalone/deployments
  extraVolumes: |
    - name: deployments
      emptyDir: {}

prometheus:
  operator:
    ## Are you using Prometheus Operator?
    enabled: true

    serviceMonitor:
      ## Optionally set a target namespace in which to deploy serviceMonitor
      namespace: "keycloak"

      ## Additional labels to add to the ServiceMonitor so it is picked up by the operator.
      ## If using the [Helm Chart](https://github.com/helm/charts/tree/master/stable/prometheus-operator) this is the name of the Helm release.
      selector:
        release: prometheus-operator

      ## Interval at which Prometheus scrapes metrics
      interval: 10s

      ## Timeout at which Prometheus timeouts scrape run
      scrapeTimeout: 10s

      ## The path to scrape
      path: /auth/realms/master/metrics
```

```
#  set {
#    name  = "keycloak.extraArgs"
#    value = "-Dkeycloak.profile=preview -Dkeycloak.profile.feature.upload_scripts=enabled"
#  }
#
#  set {
#    name  = "keycloak.replicas"
#    value = var.keycloak_replicas
#  }
#
#  set {
#    name  = "keycloak.persistence.dbVendor"
#    value = "mysql"
#  }
#
#  set {
#    name  = "keycloak.persistence.dbName"
#    value = var.keycloak_db_name
#  }
#
#  set {
#    name  = "keycloak.persistence.dbUser"
#    value = var.keycloak_db_user
#  }
#
#  set {
#    name  = "keycloak.persistence.dbHost"
#    value = var.keycloak_db_host
#  }
#
#  set {
#    name  = "keycloak.persistence.dbPort"
#    value = var.keycloak_db_port
#  }
#
#  set_sensitive {
#    name  = "keycloak.persistence.dbPassword"
#    value = local.keycloak_db_password
#  }
#
#  set_sensitive {
#    name  = "keycloak.password"
#    value = local.keycloak_password
#  }
#
#  values = [
#    data.template_file.values.rendered,
#  ]
#  depends_on = [kubernetes_namespace.keycloak]
```
9.9.1 value
```yaml
extraInitContainers: |
  - name: extensions
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
      - sh
    args:
      - -c
      - |
        echo "Copying extensions..."
        wget -O /deployments/keycloak-metrics-spi.jar https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.0.1/keycloak-metrics-spi-2.0.1.jar
    volumeMounts:
      - name: deployments
        mountPath: /deployments
extraVolumeMounts: |
  - name: deployments
    mountPath: /opt/jboss/keycloak/standalone/deployments
extraVolumes: |
  - name: deployments
    emptyDir: {}

postgresql:
  # Disable PostgreSQL dependency
  enabled: false

args: 
  - -Dkeycloak.profile=preview -Dkeycloak.profile.feature.upload_scripts=enabled

extraEnv: |
  - name: JDBC_PARAMS
    value: enabledTLSProtocols=TLSv1.2
  - name: KEYCLOAK_USER
    value: keycloak
  - name: KEYCLOAK_PASSWORD
    value: '{{ .Values.password }}'
  - name: DB_VENDOR
    value: '{{ .Values.dbVendor}}'
  - name: DB_ADDR
    value: '{{ .Values.dbHost }}'
  - name: DB_PORT
    value: '{{ .Values.dbPort }}'
  - name: DB_DATABASE
    value: '{{ .Values.dbName }}'
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS
      -Djava.awt.headless=true

extraEnvFrom: |
  - secretRef:
      name: '{{ include "keycloak.fullname" . }}-db'

secrets:
  db:
    stringData:
      DB_USER: '{{ .Values.dbUser }}'
      DB_PASSWORD: '{{ .Values.dbPassword }}'


```
```
data "template_file" "values" {
  template = file("${path.module}/values.tpl")
}

#resource "helm_release" "keycloak" {
#  name = var.keycloak_ns
#
#  repository = "https://codecentric.github.io/helm-charts"
#  chart      = "keycloak"
#  version    = var.keycloak_chart_version
#  namespace  = var.keycloak_ns
#
#  set {
#    name  = "keycloak.extraArgs"
#    value = "-Dkeycloak.profile=preview -Dkeycloak.profile.feature.upload_scripts=enabled"
#  }
#
#  set {
#    name  = "replicas"
#    value = var.keycloak_replicas
#  }
#
#  set {
#    name  = "serviceMonitor.enabled"
#    value = "true"
#  }
#
#  set {
#    name  = "serviceMonitor.namespace"
#    value = var.keycloak_ns
#  }
#
#  set {
#    name  = "serviceMonitor.namespaceSelector"
#    value = {prometheus-operator}
#  }
#  set {
#    name  = "serviceMonitor.interval"
#    value = "10s"
#  }
#
#  set {
#    name  = "serviceMonitor.scrapeTimeout"
#    value = "10s"
#  }
#
#  set {
#    name  = "serviceMonitor.path"
#    value = "/auth/realms/master/metrics"
#  }   
#
#
#  set {
#    name  = "dbVendor"
#    value = "mysql"
#  }   
#
#  set {
#    name  = "dbName"
#    value = var.keycloak_db_name
#  }
#
#  set {
#    name  = "dbUser"
#    value = var.keycloak_db_user
#  }
#
#  set {
#    name  = "dbHost"
#    value = var.keycloak_db_host
#  }
#
#  set {
#    name  = "dbPort"
#    value = var.keycloak_db_port
#  }
#
#  set_sensitive {
#    name  = "dbPassword"
#    value = local.keycloak_db_password
#  }
#
#  set_sensitive {
#    name  = "password"
#    value = local.keycloak_password
#  }
#
#  values = [
#    data.template_file.values.rendered,
#  ]
#  depends_on = [kubernetes_namespace.keycloak]
#}
```
