### ISSUE TITLE
Keycloak 5.0.0 Chart: specify  keycloak.persistence.deployPostgres: false and postgres is still deployed

### ISSUE THREAD

**Issue by enenum** [codecentric/helm-charts#40]
Was using keycloak 4.0 chart with with the above flawlessly and installing postgres separately.
With the new 5.0 chart, I end up with two deployments of postgres.

Helm & Tiller 2.11.0
Kubernetes 1.13 cluster installed with Kubespray 2.8

**Comment by unguiculus** [comment]
There has been no change regarding the dependency. Please share your configuration so I can help.

**Comment by unguiculus** [comment]
Closing due to inactivity.

**Comment by rblaine95** [comment]
Hi there, I'm having the same issue over here with chart version `5.1.5`

```sh
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.11.0+3b2d3b6-227
kubernetes v1.11.0+d4cacc0
```
```yaml
keycloak:
  persistence:
    deployPostgres: false
    dbVendor: postgres
    dbName: keycloak
    dbHost: kubedb-postgres
    dbPort: 5432
    dbUser: keycloak
    dbPassword: keycloak
```

Maybe I'm just missing something?
