### ISSUE TITLE
Keycloak - how to load realm config on startup?

### ISSUE THREAD

**Issue by manuschillerdev** [codecentric/helm-charts#407]
Currently I am trying to load a custom Realm Config on startup. 

Conf:
```json
{
  "realm": "test-realm",
  "id": "test-realm",
  "enabled": "true",
  "revokeRefreshToken": true,
  "accessTokenLifespan": 900,
  "passwordPolicy": "length(8) and digits(1) and specialChars(1)",
  "roles": {
    "realm": [
      {
        "id": "c9253f52-1960-4c9d-af99-5facca0c0845",
        "name": "admin",
        "description": "admin role",
        "scopeParamRequired": false,
        "composite": false,
        "clientRole": false,
        "containerId": "test-realm"
      }
    ]
  }
}
```
Then I generate a config-map from the file via:
```bash
kubectl create configmap test --from-file realm.json --dry-run=client -o yaml
```

```yaml
apiVersion: v1
data:
  realm.json: |
    {
      "realm": "test-realm",
      "id": "test-realm",
      "enabled": "true",
      "revokeRefreshToken": true,
      "accessTokenLifespan": 900,
      "passwordPolicy": "length(8) and digits(1) and specialChars(1)",
      "roles": {
        "realm": [
          {
            "id": "c9253f52-1960-4c9d-af99-5facca0c0845",
            "name": "admin",
            "description": "admin role",
            "scopeParamRequired": false,
            "composite": false,
            "clientRole": false,
            "containerId": "test-realm"
          }
        ]
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: test
```

I think I would need to reference this config-map somehow at https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/values.yaml#L189 

Is my approach feasible, and how would I load the config in my Keycloak Pod?
