### ISSUE TITLE
How do I configure a User storage provider to enable User Federation?

### ISSUE THREAD

**Issue by StymiedSloth** [codecentric/helm-charts#422]
Hello
How do I go about configuring a [User Storage SPI](https://www.keycloak.org/docs/latest/server_development/#_user-storage-spi)

We have an external data store for our identities and would like to connect Keycloak to that using the Storage SPI linked above. 

My basic thought is this is another SPI similar to themes but I can't find much more detail that to configure using the helm chart.

Please guide me here.
Thank you

Related Docs on User Federation 
https://www.keycloak.org/docs/latest/server_admin/index.html#_user-storage-federation

**Comment by StymiedSloth** [comment]
Add this to your values yaml.

This config copies a `jar` of a storage provider (in the storage_providers directory in your image) to `/opt/jboss/keycloak/standalone/deployments`

```yaml
  - name: storage-providers
    image: <your-image-tag>
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 1000
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    command:
      - sh
    args:
      - -c
      - |
        echo "Copying user storage providers..."
        cp -R /storage_providers/* /storage-providers
    volumeMounts:
      - name: storage-providers
        mountPath: /storage-providers
extraVolumeMounts: |
  - name: storage-providers
    mountPath: /opt/jboss/keycloak/standalone/deployments
extraVolumes: |
  - name: storage-providers
    emptyDir: {}
```
