### ISSUE TITLE
Unable to connect to production mysql running on aws

### ISSUE THREAD

**Issue by iamaverrick** [codecentric/helm-charts#423]
hello great chart, 

We are trying to use this helm chart in production environment without the the PostgreSQL dependency because it isn't suitable for production . so we have a production grade mysql database running which we will like to use but don't seem to find much information in regards to what database can be used by the chart nor ways to connect to them. 

this is my current configuration 

```
postgresql:
  # If `true`, the Postgresql dependency is enabled
  enabled: false

# Add additional volumes, e. g. for custom themes
extraVolumes: |
  - name: secrets
    secret:
      secretName: keycloak-secrets

# Add additional volumes mounts, e. g. for custom themes
extraVolumeMounts: |
  - name: secrets
    mountPath: /secrets
    readOnly: true

extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_USER
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_USERNAME
  - name: KEYCLOAK_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_PASSWORD
  - name: DB_VENDOR
    value: mysql
  - name: DB_PORT
    value: "3306"
  - name: DB_DATABASE
    value: keycloak
  - name: DB_ADDR
    value: MYSQL_ADDRR.us-east-1.rds.amazonaws.com
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_DB_USERNAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_DB_PASSWORD
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
  - name: WILDFLY_LOGLEVEL
    value: DEBUG
```

i know is not the way i mounted the secrets because the username and password work find when enabling postgresql for testing purposes locally. 

can anybody please provide some guidance

lastly i seem to have an issue when liquidbase is enabled due to my other apps using the same thing. what is the option in disabling the liquidbase from keycloak

thanks in advance

**Comment by iamaverrick** [comment]
solved my issues with connecting to aws rds (mysql) using the following example provided below

  - name: JDBC_PARAMS
    value: enabledTLSProtocols=TLSv1.2

```
# Additional environment variables for Keycloak
extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_USER
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_USERNAME
  - name: KEYCLOAK_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_PASSWORD
  - name: DB_VENDOR
    value: mysql
  - name: DB_PORT
    value: "3306"
  - name: DB_DATABASE
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_DB_DATABASE
  - name: DB_ADDR
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_DB_ADDR
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_DB_USERNAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_DB_PASSWORD
  - name: JDBC_PARAMS
    value: enabledTLSProtocols=TLSv1.2
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
  - name: WILDFLY_LOGLEVEL
    value: DEBUG
```
