### ISSUE TITLE
[keycloak] private & public ingress 

### ISSUE THREAD

**Issue by iamaverrick** [codecentric/helm-charts#425]
i'm not sure if this is possible and if its not would like to submit a feature request.

We currently would like to use keycloak in private cloud and access it only using VPN, we want to expose only the endpoints that point to the public web apps that we have running and the only ones privately like jenkins, etc.

we would like to see if its possible to add another second ingress so we can expose that one to the cloud or vice versa.

Example 

```
  # often you want to have your controller all locked down and private
  # but you still want to get webhooks from your SCM
  # A secondary ingress will let you expose different urls
  # with a differnt configuration
  secondaryingress:
    enabled: true
    # paths you want forwarded to the backend
    # ex /github-webhook
    paths:
      - /bitbucket-hook
    # For Kubernetes v1.14+, use 'networking.k8s.io/v1beta1'
    apiVersion: "networking.k8s.io/v1beta1"
    labels: {}
    annotations:
      kubernetes.io/ingress.class: "nginx"
      external-dns.alpha.kubernetes.io/hostname: keycloak.company.com
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # configures the hostname e.g. keycloak.company.com
    hostName: "keycloak.company.com"
```

so the idea will be that the first one will be in the private network and only accessible to inner apps , and the second one for the public one. if this is possible with the current helm chart please advice how. thanks
