### ISSUE TITLE
[keycloak-7.4.0] 'keycloak' failed: failed to prepare chart for release: could not find : chart postgresql not found in https://kubernetes-charts.storage.googleapis.com/

### ISSUE THREAD

**Issue by mrad-bilel** [codecentric/helm-charts#431]
Hello,

I've a problem with keycloak when trying to update the helmrelease . 

Envirement:

EKS V1.16
DB AWS RDS Postgresql 

```
Type     Reason             Age                      From           Message
  ----     ------             ----                     ----           -------
  Warning  FailedReleaseSync  4m42s (x3492 over 7d6h)  helm-operator  synchronization of release 'keycloak' in namespace 'keycloak' failed: failed to prepare chart for release: could not find : chart postgresql not found in https://kubernetes-charts.storage.googleapis.com/

``` 
HelmRelease values 

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    fluxcd.io/automated: "false"
  name: keycloak
  namespace: keycloak
spec:
  chart:
    git: git@github.com:codecentric/helm-charts
    path: charts/keycloak
    ref: keycloak-7.4.0
  releaseName: keycloak
  values:
    init:
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 500m
          memory: 1024Mi
    keycloak:
      readinessProbe: |
        httpGet:
          path: {{ if ne .Values.keycloak.basepath "" }}/{{ .Values.keycloak.basepath }}{{ end }}/realms/master
          port: http
        initialDelaySeconds: 60
        timeoutSeconds: 1
      existingSecret: keycloak-creds
      existingSecretKey: keycloak-admin-password
      extraArgs: -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled
      extraInitContainers: |
        - name: theme-provider
          image: xxxxxxxxxxxx.amazonaws.com/keycloak
          imagePullPolicy: Always
          command:
            - sh
          args:
            - -c
            - |
              echo "Copying themes..."
              cp -R /mytheme/base/* /base
          volumeMounts:
            - name: base
              mountPath: /base
      extraVolumeMounts: |
        - name: base
          mountPath: /opt/jboss/keycloak/themes/base
      extraVolumes: |
        - name: base
          emptyDir: {}
      ingress:
        enabled: true
        hosts:
        - keycloak.xxxxxxxxxxxxxxxxxx
      persistence:
        dbHost: xxxxxxxxxxxxxxx.rds.amazonaws.com
        dbName: keycloakdev
        dbPort: 5432
        dbVendor: postgres
        deployPostgres: false
        existingSecret: postgresql-creds
        existingSecretPasswordKey: postgresql-db-password
        existingSecretUsernameKey: postgresql-db-user
      replicas: 0
```

Any idea please ?
