### ISSUE TITLE
Unable to redirect to /auth/admin/master/console even if ingress-console is enabled too

### ISSUE THREAD

**Issue by jasgeetsingh22** [codecentric/helm-charts#433]
I am doing deployment of keycloak using Ingress enabled, I can successfully browse to home page of Keycloak but when I click on Administration Console it will redirect me to the blank page, I also enabled ingress console from values.yaml.

What I am doing wrong here or what extra needs to be done?

**Comment by dharmendrakariya** [comment]
@jasgeetsingh22 any lead on this bro? facing the same issue

**Comment by jasgeetsingh22** [comment]
Yeah if you see in the browser console, it will say you are asking for Unsecure scripts. so you need to put the following key

  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

**Comment by dharmendrakariya** [comment]
I did that but no luck!! have u done any other extra config? at ingress level? @jasgeetsingh22

**Comment by kelayuu** [comment]
I'm facing the same issue, my ingress is setup and working with path https://keycloak.local.net/auth/, but when i try to access the admin console it redirect me to the same /auth/ page. Everything works fine when i use port-forwarding but from the ingress i don't have the good redirection.
Here is my values.yaml config, i select only the things i've changed

```yaml
image:
  repository: docker.io/jboss/keycloak
  tag: "11.0.3"
  pullPolicy: IfNotPresent
extraEnv: |
  - name: KEYCLOAK_USER
    value: "admin"
  - name: KEYCLOAK_PASSWORD
    value: "password"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
ingress:
  enabled: true
  servicePort: http
  annotations: {}
  labels: {}
  rules:
    -
      host: 'keycloak.local.net'
      paths:
        - ""
  tls:
    - hosts:
        - "keycloak.local.net"
      secretName: ""
```

i've tried this also in the ingress 
```yaml
annotations: {nginx.ingress.kubernetes.io/rewrite-target: /$1}
paths:
          - /(.*)
```
But i'm facing the same issue.

Here is a log from the ingress controller, while trying to access the console

10.0.1.221 - - [16/Jul/2021:08:13:36 +0000] "GET /auth/ HTTP/2.0" 200 4075 "https://keycloak.local.net/auth/admin/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0" 17 0.005 [default-keycloak-http-http] [] 10.244.1.51:8080 4075 0.008 200 88d30c05efe58738a659a1e4be466115

I think the problem come from the tls certificat but i have no idea what  to do ..

**Comment by dharmendrakariya** [comment]
@kelayuu 

```

   extraEnv: |
      - name: PROXY_ADDRESS_FORWARDING
        value: "true"
      - name: KEYCLOAK_HTTP_PORT
        value: "80"
      - name: KEYCLOAK_HTTPS_PORT
        value: "443"
      - name: KEYCLOAK_HOSTNAME
        value: cloak.xxx.com
      - name: KEYCLOAK_FRONTEND_URL
        value: https://cloak.xxx.com/auth
      - name: KEYCLOAK_LOGLEVEL
        value: DEBUG
      - name: WILDFLY_LOGLEVEL
        value: DEBUG
      - name: CACHE_OWNERS_COUNT
        value: "2"
      - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
        value: "2"

```

**Comment by thewhitewizard** [comment]
Hi guys,

A few months ago I had the same problem. You must provide KEYCLOAK_FRONTEND_URL

**Comment by kelayuu** [comment]
Thanks you for your answers

I've tried with of @dharmendrakariya setting but the problem is the same. 
```yaml
extraEnv: |
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://keycloak.local.net/auth/"
  - name: DB_VENDOR
    value: "h2"
  - name: KEYCLOAK_USER
    value: "admin"
  - name: KEYCLOAK_PASSWORD
    value: "password"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_HTTP_PORT
    value: "80"
  - name: KEYCLOAK_HTTPS_PORT
    value: "443"
  - name: KEYCLOAK_HOSTNAME
    value: keycloak.local.net
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
  - name: WILDFLY_LOGLEVEL
    value: DEBUG
  - name: CACHE_OWNERS_COUNT
    value: "2"
  - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
    value: "2"
```
I believe the problem is not coming from then env variables because it work perfectly with a port-forward on 8080 on localhost. 
I've fetched the chart and remove all tls from the ingress.yaml and values.yaml but it's still in https. This is super weird and i have no idea where to look for ...

Thanks for you time ^^
