### ISSUE TITLE
how can I see /metrics ?

### ISSUE THREAD

**Issue by Hokwang** [codecentric/helm-charts#434]
Hi,

based of https://github.com/keycloak/keycloak-containers/blob/master/server/README.md#enable-some-metrics,
I use 
```
extraEnv: |
  - name: KEYCLOAK_STATISTICS
    value: all
```

and also I use `ingress.rules.paths`.
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  rules:
    - host: company.com
      paths:
        - /keycloak-stage
``` 

I can't find `/metrics` url. I think it will be `/keycloak-stage/metrics`, but
it shows me
```
We are sorry...
Page not found
```
