### ISSUE TITLE
Enhance Keycloak helm to support overlays better

### ISSUE THREAD

**Issue by Boojapho** [codecentric/helm-charts#437]
## Problem

Many of the values, like `extraVolumes` and `extraEnv`, are string based and passed through a template.  This makes it very flexible from a templating.  But, it has a downside of preventing meaningful overlays since the entire string must be overwritten.  

As an example if I have this in `values.yaml`:
```yaml
extraEnv: |-
  - name: CACHE_OWNERS_COUNT
    value: "2"
```

And I want an overlay in `myvalues.yaml`:
```yaml
extraEnv: |-
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
```

I run into a problem because I am overwriting the CACHE_OWNERS_COUNT environmental variable.

## Proposed Solution

I'd like to propose we modify the value to use maps instead of strings, but still provide templating for the values.
> NOTE: This would be a breaking change, unless you create a new variable to allow both methods.

For example, in `values.yaml`:
```yaml
extraEnv:
  CACHE_OWNERS_COUNT: "2"
```

And for the overlay in `myvalues.yaml`:
```yaml
extraEnv:
  KEYCLOAK_LOGLEVEL: DEBUG
```

The values could still be templated by using:
```
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 2 }}
  {{- end }}
```

And in `values.yaml`:
```yaml
extraEnv:
  KEYCLOAK_LOGLEVEL: '{{ .Values.loglevel }}'
  WILDFLY_LOGLEVEL: '{{ .Values.loglevel }}'
```

### More complex example

Here is how volume mounts could be templated in the Helm chart:

`values.yaml`
```yaml
extraVolumeMounts:
  certauthority:
    mountPath: /etc/x509/https/cas.pem
    subPath: cas.pem
    readOnly: true
  customreg:
    mountPath: /opt/jboss/keycloak/customreg.yaml
    subPath: customreg.yaml
    readOnly: true
```

Snippet in `statefulset.yaml`:
```
  {{- range $key, $value := .Values.extraVolumeMounts }}
  - name: {{ $key }}
  {{- range $subkey, $subvalue := . }}
    {{ $subkey }}: {{ if (typeIs "string" $subvalue) }}{{ tpl $subvalue $ }}{{ else }}{{ $subvalue }}{{ end }}
  {{- end }}
  {{- end }}
```

## Scope of Change

Here is a list of variables that would be affected by addressing this issue:
- extraEnv
- extraVolumes
- extraVolumeMounts
- extraInitContainers
- extraContainers

And maybe...
- lifecycleHooks
- extraEnvFrom
- affinity
- livenessProbe
- readinessProbe
- startupProbe
