### ISSUE TITLE
Keyloak with external PGSQL

### ISSUE THREAD

**Issue by abdel1979** [codecentric/helm-charts#438]
Hi

###################
```
postgresql:
  # Disable PostgreSQL dependency
  enabled: false

extraEnv: |
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: xxx
  - name: DB_PORT
    value: "5432"
  - name: DB_DATABASE
    value: xxx
  - name: DB_USER_FILE
    value: /secrets/db-creds/user
  - name: DB_PASSWORD_FILE
    value: /secrets/db-creds/password

extraVolumeMounts: |
  - name: db-creds
    mountPath: /secrets/db-creds
    readOnly: true

extraVolumes: |
  - name: db-creds
    secret:
      secretName: keycloak

```
#################
The keycloak secret has two fields : DB_USER and DB_PASSWORD

########

ERROR when deploying the chart 
```
k logs pods/keycloak-1 
-b 0.0.0.0
/opt/jboss/tools/docker-entrypoint.sh: line 20: /secrets/db-creds/user: No such file or directory
```
