### ISSUE TITLE
extraEnv substitution (feature request)

### ISSUE THREAD

**Issue by hchan** [codecentric/helm-charts#459]
I want the ability to have the extraEnv variable merge between to values files.
i.e. if I have values.yaml and values-secrets.yaml, I want values-secrets.yaml to merge certain PASSWORDs to values.yaml

**Comment by beastob** [comment]
May I confirm if the following scenario is what you expected.
Let's assume the default values.yaml contains:
```yaml
## values.yaml 
extraEnv:
  - name: KEYCLOAK_LOGLEVEL
    value: DEBUG
  - name: WILDFLY_LOGLEVEL
    value: DEBUG
  - name: CACHE_OWNERS_COUNT
    value: "2"
  - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
    value: "2"
```
And your own custom values to override
```yaml
## values-custom.yaml
extraEnv:
  - name: KEYCLOAK_LOGLEVEL
    value: INFO
  - name: WILDFLY_LOGLEVEL
    value: INFO
  - name: PASSOWRD
    value: 'changeme'
  - name: USERNAME
    value: admin
```
The result combined values for the Helm chart would be:
```yaml
## combined values
extraEnv:
  - name: KEYCLOAK_LOGLEVEL
    value: INFO
  - name: WILDFLY_LOGLEVEL
    value: INFO
  - name: CACHE_OWNERS_COUNT
    value: "2"
  - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
    value: "2"
  - name: PASSOWRD
    value: 'changeme'
  - name: USERNAME
    value:  #admin
```
