### ISSUE TITLE
[keycloak] Wrong port when click on manage account

### ISSUE THREAD

**Issue by Igor-lkm** [codecentric/helm-charts#473]
Chart version: `15.0.0`

**Setup**: 
I have keycloak behind a proxy (kong). Keycloak ports are set to `80` and `443` via env variables. It is necessary to set these port to make keycloak work behind a proxy - [Related issue on stackoverflow](https://stackoverflow.com/questions/55164687/keycloak-behind-kong-and-strange-redirect/58306107#58306107)

**Problem**:
When I log into `Administration Console` (yep i can login and go though menus, everything seems to work) and click `Manage account` on the right top, keycloak redirects me to `http://auth.example.com:8443/auth/realms/master/account/?referrer=security-admin-console`. So the port is wrong here... it should be picked from `KEYCLOAK_HTTPS_PORT`, but it's not.

**Expected behavior:**
Not to have port `8443` and just go to `http://auth.example.com/auth/real...`

**Relevant part of my `value.yaml`:** 

```
resources: *
replicas: *
postgresql:
  enabled: false
extraEnv: |
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KEYCLOAK_HTTP_PORT
    value: "80"
  - name: KEYCLOAK_HTTPS_PORT
    value: "443"
  - name: KEYCLOAK_HOSTNAME
    value: auth.example.com
  - name: KEYCLOAK_FRONTEND_URL
    value: https://auth.example.com/auth
  - name: DB_VENDOR
    value: postgres
  - name: DB_ADDR
    value: *
  - name: DB_PORT
    value: *
  - name: DB_DATABASE
    value: *
  - name: DB_USER_FILE
    value: /secrets/db-creds/user
  - name: DB_PASSWORD_FILE
    value: /secrets/db-creds/password

extraVolumeMounts: ...
extraVolumes: ...

```

Thank you folks!
