### ISSUE TITLE
AWS ALB controller with keycloak ingress definition does not support fixed responses

### ISSUE THREAD

**Issue by ykov** [codecentric/helm-charts#479]
Hi 
we are using AWS ALB controller with a fixed-response definition, e.g
```
alb.ingress.kubernetes.io/actions.response-503: >
      {"type":"fixed-response","fixedResponseConfig":{"contentType":"text/plain","statusCode":"503","messageBody":"503 error text"}}
spec:
  rules:
    - http:
        paths:
          - path: /503
            backend:
              serviceName: response-503
              servicePort: use-annotation
```
(https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#actions)

It looks like the keycloak ingress definition always replaces the name and the port with "name-http", "port"
which prevents this kind of definition "response-503", "use-annotation", as they are always replaced
```
rules:
    {{- range .Values.ingress.console.rules }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "keycloak.fullname" $ }}-http
                port:
                  name: {{ $ingress.servicePort }}
            {{- else }}
            backend:
              serviceName: {{ include "keycloak.fullname" $ }}-http
              servicePort: {{ $ingress.servicePort }}
            {{- end }}
          {{- end }}
    {{- end }}
```
Can you pls also allow fixed-responses-kind of definitions
