### ISSUE TITLE
Custom keycloak theme is not visible in theme list

### ISSUE THREAD

**Issue by exaucae** [codecentric/helm-charts#480]
I have set a custom theme config in my keycloak helm values.yml file according to this repo guidance, but when restarting the server I don't see my `customTheme` in the theme list.

This is a possible duplicate of  #200  . But no solution or hint was provided there, as of today .

My relevant setup is listed below:

1.  Custom Theme folder structure
````
parentDir
  └─customTheme
     └───login
        └───resources
           └───static
               ├───css
               ├───js
               └───media
         ─theme.properties
         ─template.ftl
   ─Dockerfile
````

2.  Dockerfile

````sh
FROM busybox

COPY customTheme  /customTheme

````
Image is well generated

3.  Relevant Helm config

```yaml

extraInitContainers: |
  - name: theme-provider
    image: myprivateregistry/customTheme:latest
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
      - name: pull-secret-name-here

    command:
      - sh
    args:
      - -c
      - |
        echo "Copying custom  keycloak theme..."
        cp -R /customTheme/* /theme
    volumeMounts:
      - name: theme
        mountPath: /theme

extraVolumeMounts: |
  - name: theme
    mountPath: /opt/jboss/keycloak/themes/customTheme

extraVolumes: |
  - name: theme
    emptyDir: {}

```

Versions: 
- keycloak: 15.0.0

**Comment by exaucae** [comment]
Related to #237 . Use a public registry or just stick with the workaround described in #237 .

**Comment by exaucae** [comment]
Update : works well with this setup ( see how I moved the pullSecret )


```yml

extraInitContainers: |
  - name: theme-provider
    image: myprivateregistry/customTheme:latest
    imagePullPolicy: IfNotPresent


    command:
      - sh
    args:
      - -c
      - |
        echo "Copying custom  keycloak theme..."
        cp -R /customTheme/* /theme
    volumeMounts:
      - name: theme
        mountPath: /theme

extraVolumeMounts: |
  - name: theme
    mountPath: /opt/jboss/keycloak/themes/customTheme

extraVolumes: |
  - name: theme
    emptyDir: {}

 imagePullSecrets:
      - name: secret-name-here

```
