### ISSUE TITLE
postgresql persistence does not work anymore

### ISSUE THREAD

**Issue by jaschaschmidt** [codecentric/helm-charts#494]
I used the following settings in the values.yaml in my previous installation and it worked fine.
But it does not seem to be considered by the new helm chart.
Could you please advise how to fix this?

```
postgresql:
  # If `true`, the Postgresql dependency is enabled
  enabled: true
  
  # Persistent Volume Storage configuration
  persistence:
    enabled: true
```
