### ISSUE TITLE
Service urls are returned with HTTP instead of HTTPS

### ISSUE THREAD

**Issue by gionapaolini** [codecentric/helm-charts#498]
When I make a request to `https://{host}/auth/realms/{realm}` I get:
```
realm: ...
public_key: ...
token-service: "http://{host}/auth/realms/{realm}/protocol/openid-connect"
account-service: "http://{host}/auth/realms/{realm}/account"
tokens-not-before: ..
```
What I expect is:
```
realm: ...
public_key: ...
token-service: "https://{host}/auth/realms/{realm}/protocol/openid-connect"
account-service: "https://{host}/auth/realms/{realm}/account"
tokens-not-before: ..
```

My value file already contains:
```
- name: PROXY_ADDRESS_FORWARDING
  value: true
```

And this is the Ingress configuration:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-redirect-from: http
    nginx.ingress.kubernetes.io/proxy-redirect-to: https
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" 
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-For {host}";
      more_set_headers "X-Forwarded-Proto https";
  name: ingress-openid
spec:
  rules:
  - http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: api-gateway-oauth2-proxy
            port:
              name: http
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: release-ke-http
            port: 
              name: https
      ...
```
Anybody knows why it's still using http in response?
