### ISSUE TITLE
"invalid Yaml document separator" error with helm 3.7.1

### ISSUE THREAD

**Issue by lemeurherve** [codecentric/helm-charts#504]
When trying to install codecentric/keycloak:15.1.0 with helm 3.7.1 with 2 or more secrets, I've got this error:
> [ERROR] templates/secrets.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: v1

This error isn't triggered with helm 3.6.3

Corresponding `values.yaml` to reproduce:
```
secrets:
  db:
      data:
          DB_USER: YWRtaW4=
          DB_PASSWORD: cGFzc3dvcmQ=
  http:
      data:
          KEYCLOAK_USER: YWRtaW4=
          KEYCLOAK_PASSWORD: cGFzc3dvcmQ=
```

> $ helm lint   
> ==> Linting .
> [ERROR] templates/secrets.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: v1
> 
> Error: 1 chart(s) linted, 1 chart(s) failed
