### ISSUE TITLE
High Availability: Unable to Logon to the Keycloak admin console (GKE)

### ISSUE THREAD

**Issue by vsomasvr** [codecentric/helm-charts#51]
This is an **issue** with the version 4.14.2 that I am finding on making HA mode work on GKE platform.

1) I tried installing the chart on GKE platform.
2) I tried the default chart with 1 replica and it worked perfectly.
3)Then I purged the chart, and set the replicas=3 and installed again.

All replicas came up, But, when I tried to login, the login fails, it comes back with messages such as
**"You are already logged in."**
But, it does not load the logged in page.

The only values I have changed were
```
keycloak:
  replicas: 3
service:
  type: NodePort
```

I used the following as Ingress on GKE

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

  labels:
    app: keycloak
    release: keycloak
spec:
  tls:
    - secretName: authcen-tls
  rules:
    - http:
        paths:
          - path: /auth
            backend:
              serviceName: keycloak-http
              servicePort: http
```
When I performed the above change
I had seen log
 `Finished rebalance with members [keycloak-0, keycloak-2, keycloak-1]`
which gave an indication that cluster formed successfully, But it failed during run time, with message as follows
`ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-9) Uncaught server error: java.lang.NullPointerException\n\tat org.keycloak.protocol.oidc.endpoints.TokenEndpoint.codeToToken(TokenEndpoint.java:300)`

I felt that I am missing something here, Can anyone please let me know the steps to make HA mode working? (I tried it long before with 4.0 version which was working fine)

**Comment by vsomasvr** [comment]
My apologies, there was no issue with the chart wrt. HA mode.
I debugged it further and found that there was an issue with ingress I was creating (along with the certs) which I guess interfered with the way redirects happen.
I found no issues with replicas=2

with the ingress manifest as follows

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    #kubernetes.io/ingress.global-static-ip-name: authcen-static-ip # enable for static-ip

  labels:
    app: keycloak
    chart: keycloak-4.14.2
    heritage: Tiller
    release: keycloak
spec:
  rules:
  - host: auth.example.com
    http:
      paths:
      - backend:
          serviceName: keycloak-http
          servicePort: http
        path: /*
  tls:
  - secretName: authcen-tls
```
