### ISSUE TITLE
[Keycloak] Why is Chart Version 16 and App Version 15

### ISSUE THREAD

**Issue by Tim-Schwalbe** [codecentric/helm-charts#517]
Why is Chart Version 16 and App Version 15?

**Comment by grafjo** [comment]
@Tim-Schwalbe maybe there was a breaking change the keycloak chart, so a major version bump was required.

**Comment by Jay-Funk** [comment]
@grafjo if that is the case please update the documentation accordingly clearly states that the **default is the chart version:**
``` yaml
image:
  # The Keycloak image repository
  repository: docker.io/jboss/keycloak
  # Overrides the Keycloak image tag whose default is the chart version
  tag: ""
```
