### ISSUE TITLE
[keycloak] - admin web gui not accessible - /auth/admin or /admin - gives 404

### ISSUE THREAD

**Issue by owit-infra** [codecentric/helm-charts#542]
I tried various ways of deploying the keycloak chart version 17.0.1 - and when it gets deployed I cannot access the admin page on paths: 
/admin 
or 
/auth/admin

it gives error 404. 
I tried enabling the console with consoe.enabled: true. that just creates an ingress which targets the HTTP port of the service (just like the original ingress) it doesn't change the behaviour and still gives 404. I also tried to change the additionally created console ingress target port to 9900 - that gives 502 Bad gateway error. 

I tried deploying a default helm chart, with no options changed other than to add ingress. Same outcome. 

I tried deploying the deault helm chart, but with ALL deaulf values - then I created an ingress resrouces for it manually. Same outcome. error 404.  

ALL of these scenarios - KeyCloak does respond on the /auth path just fine. Its only when tryng to login to the console it fails. 

I tried to look through the documetnation and can't see any specific settings I need to change to make this to work. 

Am i missing somthing obvious here ?

**Comment by grafjo** [comment]
maybe you can provide your values.yaml - so we can see what you did or didn't

**Comment by volaralle** [comment]
It works for me:
```
ingress:
  enabled: true
  servicePort: http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    app.kubernetes.io/instance: keycloak
  rules:
  - host: name.demo.com
    paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - name.demo.com
      secretName: keycloak-tls-prod
  console:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rules:
    -
      host: name.demo.com
      paths:
        - path: /auth/admin/
          pathType: Prefix
    tls:
    - hosts:
      - name.demo.com
      secretName: keycloak-tls-prod  
```

with
```
extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD
    value: asdfasdf
  - name: PROXY_ADDRESS_FORWARDING
    value: "true" 
```
