### ISSUE TITLE
Metrics scraping broken when network policy enabled

### ISSUE THREAD

**Issue by cablespaghetti** [codecentric/helm-charts#546]
With the following configuration I am unable to scrape metrics from my prometheus instance in another namespace. This is because the extraFrom parameter for the network policy only exposes ports 8080 and 8443, not 9090. 

I imagine this was done for security reasons, as generally you wouldn't want the admin port exposed outside of the namespace, but in this case it is necessary.

```
    networkPolicy:
      enabled: true
      extraFrom:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability

    postgresql:
      networkPolicy:
        enabled: true

    serviceMonitor:
      enabled: true
```

The resulting part of the network policy looks like
```
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: observability
    ports:
    - port: 8080
      protocol: TCP
    - port: 8443
      protocol: TCP
```
