### ISSUE TITLE
[keycloak] Ingress path templating

### ISSUE THREAD

**Issue by poconnor-lab49** [codecentric/helm-charts#547]
There is an example in the README.md of [changing the context path](https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#changing-the-context-path). Is there a similar way change the ingress path following the same pattern?

```yaml
ingress:
  enabled: true
  ingressClassName: nginx
  rules:
    - host: example.com
      paths:
        - path: /{{ .Values.contextPath }}(/|$)(.*)
          pathType: ImplementationSpecific
```

I couldn't come up with any obvious solution.  Would it be reasonable to template the path here since  `host` is already templated.
