### ISSUE TITLE
Invalid value for label app.kubernetes.io/version when using image digest

### ISSUE THREAD

**Issue by robert-nemet** [codecentric/helm-charts#555]
If keycloak is managed by ArgoCD and we use digest strategy to update the latest image image tag is changed to the `<tagname>:sha256:<sha value>`. While this is valid when setting image for container it is invalid for label value because it contains characters `@` and `:`. As well it should be truncated to 63 chars.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-keycloa
  labels:
    helm.sh/chart: keycloak-17.0.2
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "master@sha256:72ef973fd6d3f3e6cea8a9e1b5cbac6daf1bf8cc3d8871cbd"
    app.kubernetes.io/managed-by: Helm
imagePullSecrets:
    []
```
