### ISSUE TITLE
SUGGEST: Keycloak-X : Set cache stack to kubernetes by default.

### ISSUE THREAD

**Issue by ramneekers** [codecentric/helm-charts#576]
In `values.yaml`.

```yaml

cache:
  # Use "custom" to disable automatic cache configuration
  stack: default
```

to this

```

cache:
  # Use "custom" to disable automatic cache configuration
  stack: kubernetes
```

Fits the purpose of a helm chart more?
