### ISSUE TITLE
[keycloakx] KC_DB_URL_PORT does not exist

### ISSUE THREAD

**Issue by hertfelder** [codecentric/helm-charts#579]
Hi team,

The configuration parameter to set the port for the DB does not (yet) exist (tested with Postgres and non-standard port):
https://github.com/codecentric/helm-charts/blob/113b0fb28c755ef9830732ee55320d538af5bb64/charts/keycloakx/templates/statefulset.yaml#L106-L109

I also could not find it in the [docs](https://www.keycloak.org/server/all-config#_database).

Workaround for me was to set `KC_DB_URL` via an additional env parameter:
```yaml
[...]
# Additional environment variables for Keycloak
extraEnv: |
  - name: KC_DB_URL
    value: "jdbc:postgresql://postgres.foo.bar:64000/db?currentSchema=keycloak"
[...]
```
This way I also could set the schema.
