### ISSUE TITLE
[keycloakx] KC_DB_USERNAME_FILE not working

### ISSUE THREAD

**Issue by jeromewaibel** [codecentric/helm-charts#580]
When using KC_DB_USERNAME_FILE/KC_DB_PASSWORD_FILE with file mounted secrets as stated in the section "Using an Existing Secret" keycloak was unable to connect to the database due to invalid password.

Using
```
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: password 
```
with the same secret is working fine.

According to https://www.keycloak.org/server/configuration KC_DB_PASSWORD_FILE would be mapped to config option  `db-password-file` which is nowhere mentioned in https://www.keycloak.org/server/all-config. Is this feature really supposed to work this way?

Chart 1.3.0, Keycloak 17.0.1
