### ISSUE TITLE
Does KeycloakX support Keycloak 18.0.0?

### ISSUE THREAD

**Issue by ramneekers** [codecentric/helm-charts#586]
Hello,

We'd like to migrate to version 18.0.0 as soon as possible. Since 17.0.0 to 18.0.0 for Keycloak X is a (relatively) minor version change compared to Keycloak to KeycloakX, what specific changes should we look out for in this helm chart?

**Comment by gldraphael** [comment]
I'm new to keycloak, but it appears to be working so far. Here is my `values.yaml`:

```yaml
image:
  tag: 18.0.0
dbchecker:
  enabled: true
database:
  vendor: postgres
  hostname: server.postgres.database.azure.com
  port: 5432
  database: keycloak-exp-01
  # username: keycloakdbadmin
  # password: keycloaklocal-db-password@azurekeyvault
command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start"
  - "--auto-build"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname=login.example.org"
  - "--proxy=passthrough"
  - "--hostname-strict-https=false"
  - "--spi-events-listener-jboss-logging-success-level=info"
  - "--spi-events-listener-jboss-logging-error-level=warn"
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: adminusername
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: adminpassword
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.awt.headless=true
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-db-creds
        key: password
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-db-creds
        key: user
```
