### ISSUE TITLE
What is the default DB_USERNAME and DB_PASSWORD for Postgresql? How to change it.

### ISSUE THREAD

**Issue by ramneekers** [codecentric/helm-charts#595]
On upgrading from Keycloak 16.0.0 to 17.1.0 Quarkus in Kubernetes, we found that these parameters
```
  database:
    vendor: postgres
    username: admin
    password: keycloak
```
no longer worked. Instead, the default user/password implementation switched to `keycloak` and `keycloak`. Why does this happen?
