### ISSUE TITLE
Account console does not load

### ISSUE THREAD

**Issue by pat-s** [codecentric/helm-charts#613]
Keycloak: 18.1.1
HA: yes

```yml
    name  = "extraEnv"
    value = <<-EOT
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_FRONTEND_URL
          value: "https://${var.KEYCLOAK_DOMAIN}.${var.DNS_DOMAIN}/auth/"
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: ${module.postgres.db_instance_address}
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: keycloakdb
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: ${data.vault_generic_secret.keycloak-admin-pass.data["value"]}
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: kubernetes.KUBE_PING
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CACHE_OWNERS_COUNT
          value: "2"
        - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
          value: "2"
```

When accessing `https://<url>/auth/realms/<realm>/account/` we get

![image](https://user-images.githubusercontent.com/8430564/174090736-c1a6c409-be41-4eea-a9b5-ee8d68a8b03a.png)

"User-Managed Access" under "Realm settings" is on. Is the issue on our side?

We have been running a single docker deployment before and haven't faced this issue.
