### ISSUE TITLE
INSTALLATION FAILED: values don't meet the specifications affinity: Invalid type. Expected: string, given: object

### ISSUE THREAD

**Issue by vyom-soft** [codecentric/helm-charts#619]
Hello,
I am seeing following error 
`Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
keycloak:
- affinity: Invalid type. Expected: string, given: object`

I used the default helm chart as present in github. https://github.com/codecentric/helm-charts/tree/master/charts/keycloak
<img width="777" alt="image" src="https://user-images.githubusercontent.com/18686082/178730940-6eab8b57-efd7-4f15-9196-664ac7e78e69.png">

The issue is with is value file I guess
<img width="239" alt="image" src="https://user-images.githubusercontent.com/18686082/178731958-799926aa-7042-41d2-a940-fff03ee00b08.png">

# Pod affinity
```
affinity: |
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            {{- include "keycloak.selectorLabels" . | nindent 10 }}
          matchExpressions:
            - key: app.kubernetes.io/component
              operator: NotIn
              values:
                - test
        topologyKey: kubernetes.io/hostname
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              {{- include "keycloak.selectorLabels" . | nindent 12 }}
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: NotIn
                values:
                  - test
          topologyKey: failure-domain.beta.kubernetes.io/zone
```

I have seen this [7633](https://github.com/helm/charts/issues/7633)
