### ISSUE TITLE
Keycloak: Missing support for ingress annotation `kubernetes.io/backend-protocol: "https"` 

### ISSUE THREAD

**Issue by RappC** [codecentric/helm-charts#63]
Currently the ingress only allows connections to the service via unsecure backend port tcp/8080. 

To increase security we would like to allow ingress and service to connect via secure port 8443.

For that one can set the keycloak env variable `KEYCLOAK_HTTPS_PORT`. But in the template this section is missing: 

```
     containers:
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
```
