### ISSUE TITLE
[keycloakx] KC_HTTP_RELATIVE_PATH is empty

### ISSUE THREAD

**Issue by Footur** [codecentric/helm-charts#634]
When the relative path is just "/" the suffix will be trimmed and the variable KC_HTTP_RELATIVE_PATH will be empty.

```yaml
            {{- if .Values.http.relativePath }}
            - name: KC_HTTP_RELATIVE_PATH
              value: {{ tpl .Values.http.relativePath $ | trimSuffix "/" }}
            {{- end }}
```
