### ISSUE TITLE
[KeycloakX][bug] Issue setting annotations for the Headless Service

### ISSUE THREAD

**Issue by ic2hrmk** [codecentric/helm-charts#655]
Hi,

I recently started using the KeycloakX chart and got confused with the documentation:

`service.annotations | Annotations for headless and HTTP Services`

But there is no templating available for annotations in the `templates/service-headless.yaml`

Can you please add a different set of values to propagate custom annotations for the headless one as well?
Plus, I believe it would be a good idea to keep annotations for both services (HTTP / Headless) separate, so at the end of the day it would look like this:

```yaml
servicHeadless:
  annotations:
    a.b.c: value

servicHeadless:
  annotations:
    c.b.a: value
```

Thanks!
