### ISSUE TITLE
How should we deal with cache size when autoscaling keyclock?

### ISSUE THREAD

**Issue by bjethwan** [codecentric/helm-charts#660]
I have used this in production:
```
extraEnv: |
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: kubernetes.KUBE_PING
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: CACHE_OWNERS_COUNT
    value: "2"
  - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
    value: "2"
```

And
```
autoscaling:
  enabled: true
```

The documentation does mention the issue but doesn't tell how to handle the cache when it set for autoscaling
