### ISSUE TITLE
Keycloak startup probe fails when running in EKS Fargate

### ISSUE THREAD

**Issue by dgard1981** [codecentric/helm-charts#687]
I have an EKS cluster, and when running Keycloak on a node group I can get it to run successfully. However, when attempting to run Keycloak on Fargate, the `keycloak-0` pod fails to start.

```
Startup probe failed: Get "http://<fargate-node-ip>:8080/auth/": dial tcp 10.30.8.170:8080: connect: connection refused
```

Ingress is handled by the AWS Load Balancer Controller, and I notice that there is no target in the target group created by that Helm chart when running Keycloak on Fargate. Is there something else I need to add to `values.yaml` when running Keycloak in Fargate?

```yaml
ingress:
  enabled: true
  rules:
    - host: auth.mydomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: keycloak-tls
      hosts:
          - auth.mydomain.com
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: <my-acm-certificate-arn>
    alb.ingress.kubernetes.io/group.name: private
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
postgresql:
  global:
    storageClass: efs-keycloak
extraEnv: |
  - name: KEYCLOAK_USER
    valueFrom:
      secretKeyRef:
        name: keycloak-credentials
        key: username
  - name: KEYCLOAK_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-credentials
        key: password
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
```

It should be noted that when installing the [2048 game as described in the AWS knowledge centre](https://aws.amazon.com/premiumsupport/knowledge-center/eks-alb-ingress-controller-fargate/), the Fargate nodes are successfully added as targets to the target group created by AWS Load Balancer Helm chart, so running deployments that require an ingress in Fargate is absolutely possible.
