### ISSUE TITLE
Ingress rule path with custom backend name and backend port

### ISSUE THREAD

**Issue by albertogg** [codecentric/helm-charts#688]
To give a little context, I need to block public access to the `/admin/` endpoints in our Keycloak installation based on what's [recommended](https://www.keycloak.org/server/reverseproxy#_exposed_path_recommendations) by Keycloak.

In our current setup we are using the keycloak helm chart and leveraging the Ingress functionality. We are also using the [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) which interacts with the Ingress manifest. Given that the load balancer controller creates ALB listener rules from annotations with names that are [required to match](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#actions) with their `.backend.service.name` and `.backend.service.port.name`, I would like to know if the project be willing to accept a modification which allows the user to set custom values for these keys while keeping things backwards compatible.

For example:
```yaml
...
    -
      {{- if .host }}
      host: {{ tpl .host $ | quote }}
      {{- end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if $apiV1 }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- if and .backend .backend.service .backend.service.name }}
                name: {{ tpl .backend.service.name $ }}
                {{- else }}
                name: {{ include "keycloak.fullname" $ }}-http
                {{- end }}
                port:
                  {{- if and .backend .backend.service .backend.service.port .backend.service.port.name }}
                  name: {{ .backend.service.port.name }}
                  {{- else }}
                  name: {{ $ingress.servicePort }}
                  {{- end }}
...
```

Which would allow me to do something like, which will be backwards compatible with the current functionality:
```yaml
      paths:
        - path: /
          pathType: Prefix
        - path: /auth/admin
          pathType: Prefix
          backend:
            service:
              name: custom-name
              port:
                name: use-annotation
```

Resulting in:
```yaml
spec:
  rules:
    -
      host: "release-name.keycloak.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-name-keycloa-http
                port:
                  name: http
          - path: /auth/admin
            pathType: Prefix
            backend:
              service:
                name: custom-name
                port:
                  name: use-annotation
```

Thanks!
