### ISSUE TITLE
How to migrate from keycloak-18.1.1 chart to new Keycloakx chart

### ISSUE THREAD

**Issue by Mais316** [codecentric/helm-charts#690]
Hi All, 

Please advise if anyone has migrated from legacy keycloak-18.1.1 chart to new Keycloakx chart.

**Comment by LucasVanHaaren** [comment]
Hello I'm also searching for a clear documentation of how to migrate from keycloak chart to the keycloakx one.

**Comment by rokroskar** [comment]
I am currently trying this - for us, the main migration issue was the renaming of some environment variables, but apart from that it seems to work ok. Our environment is quite specific, but you can have a look at the PR if it's helpful: https://github.com/SwissDataScienceCenter/renku/pull/2904

**Comment by LucasVanHaaren** [comment]
Thank you @rokroskar, I will have a look and try on my side

**Comment by Mais316** [comment]
I was able to do the mapping as well its a matter of env that was changed
- https://www.keycloak.org/server/all-config 

```yaml
replicas: 2

podDisruptionBudget: 
  minAvailable: 1



## Overrides the default args for the Keycloak container
args: 
  - "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled"
  - "-Dkeycloak.profile.feature.upload_scripts=enabled"

# Additional environment variables for Keycloak mapped from Secret or ConfigMap
extraEnvFrom: |
  - secretRef:
      name: 'db-creds'



command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-enabled=true"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--hostname-strict-https=false"

# Additional environment variables for Keycloak
extraEnv: |
  - name: KC_LOG_LEVEL
    value: DEBUG
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL_HOST
    value: <hidden>
  - name: KC_DB_URL_PORT
    value: "5432"
  - name: KC_DB_URL_DATABASE
    value: keycloak
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  - name: JAVA_OPTS
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djava.awt.headless=true

# Pod resource requests and limits
resources: 
  requests:
    cpu: '.5'
    memory: "1024Mi"
  limits:
    cpu: '1'
    memory: "2048Mi"

ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: http
  annotations: 
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    cert-manager.io/issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/configuration-snippet: |  
      
    #   location ~* /auth/realms/[^/]+/metrics {
    #     return 403;
    #   }

  rules:
    - host: '<hidden>.com'
      paths:
        - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
          pathType: Prefix
  tls:
    - hosts:
        - <hidden>
      secretName: "keycloak-cert"

proxy:
  enabled: true
  mode: passthrough
```
