### ISSUE TITLE
helm: Defined`extraEnvFrom`'s values.schema is wrong

### ISSUE THREAD

**Issue by rlaisqls** [codecentric/helm-charts#732]
In keycloak chart and keycloakx chart, `extraEnvFrom`'s values.schema is wrong.
Statefulset manifest is using it by `{{- tpl . $ | nindent 12 }}`,  so it's type should be list to result like this.

```yaml
      envFrom:
      - configMapRef:
          name: special-config
```

https://github.com/codecentric/helm-charts/blob/9ee33665257a23c32da72f54a3d2bebc05ec348c/charts/keycloak/templates/statefulset.yaml#L107-L110

However, it is now a string type, so the definition must be modified to use an additional EnvFrom value. I want you to work on this.
