### ISSUE TITLE
Unable to add security context allowPrivilegeEscalation and capabilities.

### ISSUE THREAD

**Issue by swatikri0514** [codecentric/helm-charts#738]
Getting error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(StatefulSet.spec.template.spec.securityContext): unknown field "capabilities" in io.k8s.api.core.v1.PodSecurityContext].  
Path- https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/values.yaml

**Comment by belfhi** [comment]
I can't reproduce your issue, we set the `securityContext` like this: 
```
  values:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ "ALL" ]
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
```
and it works fine. 🤷
