### ISSUE TITLE
KeycloakX Update to 24.0.3

### ISSUE THREAD

**Issue by andrew-landsverk-win** [codecentric/helm-charts#756]
Hello!

Is there going to be an updated helm chart for the latest versions of keycloakx?

Thanks!

**Comment by RileySeaburg** [comment]
I would look toward the bitnami version.

**Comment by aschilke-cyphertech** [comment]
There are some config values that are now depreciated that this update should include. https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option

**Comment by koi8** [comment]
Not just image version, but helm chart itself also need changes because of
```
2024-05-18 20:09:59,756 WARN  [org.key.qua.run.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
    - proxy: Use proxy-headers.
```

**Comment by linonetwo** [comment]
version: 2.4.1 have

```
image:
  # The Keycloak image repository
  repository: quay.io/keycloak/keycloak
  # Overrides the Keycloak image tag whose default is the chart appVersion
  tag: "25.0.0"
```
