### ISSUE TITLE
[Keycloak] Network Policy enabling causes no connection between the pods or infini span instances

### ISSUE THREAD

**Issue by Tim-Schwalbe** [codecentric/helm-charts#758]
As soon as I activate the Network Policy I get the following warning and can not login to the admin console 
` ERR_TOO_MANY_REDIRECTS`

I am really not sure where this comes from at the moment.
The pod labels are correct as far as I see.

```
  labels:
    app.kubernetes.io/instance: keycloak-develop
    app.kubernetes.io/name: keycloakx
    apps.kubernetes.io/pod-index: "0"
    controller-revision-hash: keycloak-develop-keycloakx-76bbf97978
    statefulset.kubernetes.io/pod-name: keycloak-develop-keycloakx-0

```

Chart Version: 2.3.0
Keycloak:  22.0.4     

```
2024-04-05 11:48:54,490 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-04-05 11:48:55,694 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: keycloak-develop-keycloakx-0-38293, Site name: null
```

snippet of my Network Policy after deployment:

```

Name:         keycloak-develop-keycloakx
Namespace:    keycloak
Created on:   2024-04-05 14:48:12 +0200 CEST
Labels:       app.kubernetes.io/instance=keycloak-develop
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=keycloakx
              app.kubernetes.io/version=22.0.4
              helm.sh/chart=keycloakx-2.3.0
Annotations:  meta.helm.sh/release-name: keycloak-develop
              meta.helm.sh/release-namespace: keycloak
Spec:
  PodSelector:     app.kubernetes.io/instance=keycloak-develop,app.kubernetes.io/name=keycloakx
  Allowing ingress traffic:
    To Port: 8080/TCP
    To Port: 8443/TCP
    From:
      NamespaceSelector: name=tools
      PodSelector: app.kubernetes.io/name=ingress-nginx
    ----------
    To Port: 8080/TCP
    To Port: 8443/TCP
    From:
      PodSelector: app.kubernetes.io/instance=keycloak-develop,app.kubernetes.io/name=keycloakx
  Not affecting egress traffic
  Policy Types: Ingress

```

**Comment by Tim-Schwalbe** [comment]
I find the solution:
You need to add extra port so the cache can reach the pods also.
I also had to add custom config for my ingress and prometheus on the extraFrom part in the values.yaml

```

# Add additional ports, e. g. for admin console or exposing JGroups ports
extraPorts:
    - name: jgroups
      containerPort: 7800
      protocol: TCP
```

Here it depends on how your specific setup is.

```
  # If true, the Network policies are deployed
  enabled: true

  # Additional Network policy labels
  labels: {}

  # Define all other external allowed source
  # See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#networkpolicypeer-v1-networking-k8s-io
  extraFrom:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
        podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
```
