### ISSUE TITLE
Keycloak.X version: 2.4.1 admin console somethingWentWrong

### ISSUE THREAD

**Issue by linonetwo** [codecentric/helm-charts#777]
![图片](https://github.com/codecentric/helm-charts/assets/3746270/6ad2c665-d7ec-4350-948b-a5b1a15a9c83)

On console

```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure resource '<URL>'. This request has been blocked; the content must be served over HTTPS.
```

It seems try to query `/auth/resources/master/admin/en` with http, not https.

Modified values

```
ingress:
  enabled: true
  ingressClassName: "nginx"
  rules:
    -
      host: '{{ .Release.Name }}.xxx.site'
  tls:
    - hosts:
        - xxx.site
      secretName: "tls-secret"
dbchecker:
  enabled: true
database:
  existingSecret: "postgres-password"
  existingSecretKey: "password"
  # E.g. dev-file, dev-mem, mariadb, mssql, mysql, oracle or postgres
  vendor: postgres
  hostname: 1.1.1.1
  port: 5432
  database: keycloak
  username: keycloak
  existingSecret: postgresql-password
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-admin-password
        key: password
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
```

POD started successfully

![图片](https://github.com/codecentric/helm-charts/assets/3746270/57423419-c785-4a68-b9ca-3b3723696f06)
