### ISSUE TITLE
Keycloak restarts itself due to liquibase errors when using MySQL

### ISSUE THREAD

**Issue by tylervz** [codecentric/helm-charts#78]
I am trying to run Keycloak and have it use an external MySQL 5.6.10 instance. I have tried using the latest version of the Keycloak chart (v5.1.2) and version v5.1.1, but both result in the same outcome.

I am installing the chart using a yaml file with the following values (although I obviously changed the passwords and database host):

```
keycloak:
  username: kiwigrapefruit
  password: pword
  persistence:
    deployPostgres: false
    dbVendor: mysql
    dbName: keycloak
    dbHost: confidential.url.com
    dbPort: 3306
    dbUser: keycloak_user
    dbPassword: keycloak_password
```

It is able to connect to the database and create the tables, because the previously empty `keycloak` schema now has many tables in it (`APPLICATION_DEFAULT_ROLES`, `APP_NODE_REGISTRATIONS`, etc.).

The keycloak container keeps crashing and restarting itself. Here are the logs of the pod:

https://pastebin.com/nCNC6JuD

Here's my `kubectl version` output:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-eks-c57ff8", GitCommit:"c57ff8e35590932c652433fab07988da79265d5b", GitTreeState:"clean", BuildDate:"2019-06-07T20:43:03Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

And here's my `helm version` output:

```
Client: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.2", GitCommit:"a8b13cc5ab6a7dbef0a58f5061bcc7c0c61598e7", GitTreeState:"clean"}
```

Let me know if you need any more information.

Thanks,
Tyler

**Comment by unguiculus** [comment]
For some reason the database migration failed. Note that this is an issue that is not related to the Helm chart. Your database probably has some inconsistent state.

**Comment by tylervz** [comment]
After doing some more testing, I agree this issue is not related to the Helm chart. I get a similar error when running this docker compose file:
```
version: "3.7"
services:
  mysql:
    image: mysql:5.6.17
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

  keycloak:
    image: jboss/keycloak:6.0.1
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=mysql
      - DB_USER=keycloak         # The jboss/keycloak docker documentation says that 'keycloak' is the default value for
      - DB_PASSWORD=password     # DB_USER and 'password' the default for DB_PASSWORD. However, I needed to explicitly set
      - JDBC_PARAMS=useSSL=false # them, otherwise I was not able to run the version 6.0.1
    ports:
      # Navigate to http://localhost:8087 to access to Keycloak console
      - "8087:8080"
    depends_on:
      - mysql
    healthcheck:
      test: "curl -f http://localhost:8080/auth || exit 1"
      start_period: 10s
```
But I don't get the error if I change the MySQL image to `mysql:5.6.45`, so the issue appears to be that Keycloak (or at least the Keycloak Docker image) does not work with certain version of MySQL 5.6
