### ISSUE TITLE
KeycloakX 2.4.3 - ServiceMonitor template is broken

### ISSUE THREAD

**Issue by ShaunPTK** [codecentric/helm-charts#783]
When attempting to template the ServiceMonitor resource, Helm throws an error:

```
Error: YAML parse error on keycloakx/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.http.internalPort":interface {}(nil)}
helm.go:84: [debug] error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.http.internalPort":interface {}(nil)}
```

The following is rendered in the output YAML for the ServiceMonitor, which fails validation

```yaml
  endpoints:
    - port: {{ .Values.http.internalPort }}
      path: "/auth/metrics"
      interval: 10s
      scrapeTimeout: 10s
```

The template is incorrect at this line: https://github.com/codecentric/helm-charts/blob/5422beaff9da2828ce58680907baa419b96ac08d/charts/keycloakx/templates/servicemonitor.yaml#L35

This should read - 

``` yaml
   - port: {{ tpl .port $ }}
```

Corrected output:

```yaml
  endpoints:
    - port: http-internal
      path: "/auth/metrics"
      interval: 10s
      scrapeTimeout: 10s
```
