### ISSUE TITLE
Reverse Proxy behind the keycloak.

### ISSUE THREAD

**Issue by amfgomez1219** [codecentric/helm-charts#785]
Hi. 

is it possible to implement an NGINX reverse proxy that serves the HTTPS protocol in front of Kuberntes cluster and pod keycloakx.?

I have deployed the keycloak with HTTP protocol. 
![image](https://github.com/user-attachments/assets/6040bc35-f661-41ab-b316-a28f7dc1b2c9)

**Comment by lgladysz** [comment]
This worked for me:
```yaml
          ingress:
            enabled: true
            ingressClassName: nginx
            rules:
              -
                host: test.example.com
                paths:
                  - path: /auth/
                    pathType: Prefix
            tls:
              - hosts:
                  - test.example.com
          proxy:
            enabled: true
            mode: xforwarded
          extraEnv: |
            - name: KC_HOSTNAME
              value: test.example.com
            - name: JAVA_OPTS_APPEND
              value: >-
                -XX:MaxRAMPercentage=50.0
                -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
```
