### ISSUE TITLE
Blank page : somethingWentWrongDescription

### ISSUE THREAD

**Issue by sinaure** [codecentric/helm-charts#789]
Blank page on : https://keycloak.mydomain.com/auth/admin/master/console/

upgrading from

2.3.0 -> 2.4.4

keycloak is running on port 8080

```
    extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: JAVA_OPTS_APPEND
      value: "-Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local"
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "--verbose"
    - "start"
    - "--http-port=8080"
    - "--hostname-strict=false"
    - "--spi-events-listener-jboss-logging-success-level=debug"
    - "--spi-events-listener-jboss-logging-error-level=debug"
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      ingress.kubernetes.io/affinity: cookie
    rules:
      - host: 'keycloak.mydomain.com'
        paths:
          - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
            pathType: Prefix
    tls:
      - hosts: ['keycloak.mydomain.com']
        secretName: tls-keycloak
    console:
      enabled : false
 ```

I have no error messages on startup:

2024-08-13 13:34:13,724 INFO  [io.quarkus] (main) Keycloak 25.0.0 on JVM (powered by Quarkus 3.8.5) started in 18.705s. Listening on: http://0.0.0.0:8080. Management interface listening on http://0.0.0.0:9000.
