### ISSUE TITLE
Version 26 of Keycloak

### ISSUE THREAD

**Issue by GuilleAmutio** [codecentric/helm-charts#804]
Hello,

Is Keycloak 26.0.0 already supported by the helm chart of Keycloakx?

I am checking and there are a few changes regarding the proxy.

**Comment by j-q-in-berlin** [comment]
I also wanted to know more information about this. Are there any news?

**Comment by xueshanf** [comment]
I use helm chart version 2.6.0 and override the image tag with 26.0.7. It works with the following  values. The service  runs behind Google LB.

```
...
http:
  # For backwards compatibility reasons we set this to the value used by previous Keycloak versions.
  relativePath: "/auth"
  internalPort: http-internal
  internalScheme: HTTP
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--hostname=https://{{.Env.APP_HOST_NAME}}/auth"
dbchecker:
  enabled: true
proxy:
  enabled: true
  mode: xforwarded
  http:
    enabled: true
...
```
