### ISSUE TITLE
Add support for adding `volumeClaimTemplates` to the StatefulSet

### ISSUE THREAD

**Issue by gallolp** [codecentric/helm-charts#817]
Hi, I was wondering if you would be willing to consider the following feature proposal.

The chart currently supports adding extra volumes and volumeMounts to the Keycloak pods and it works great.
However, some users may be interested in using PersistentVolumes with a storageClass of their preference.
For example, a use case would be to deploy Keycloak to Amazon EKS using volumes with a storageClass that uses the [EFS CSI](https://github.com/kubernetes-sigs/aws-efs-csi-driver) driver.

The StatefulSet spec provides [volumeClaimTemplates](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#volume-claim-templates) to achieve this.

The idea is to add a `volumeClaimTemplates` value much in the same way as `extraVolumes`. Then they can be used in `extraVolumeMounts` by name just like volumes.

An example illustrating both:

```yaml
# Add additional volumes, e. g. for custom themes
extraVolumes: |
  - name: {{ include "keycloak.fullname" . }}-static-vol
    emptyDir:
      sizeLimit: 512Mi

# Add volume claim templates to the StatefulSet, e. g. for dynamic provisioning
volumeClaimTemplates: |
  - metadata:
      name: {{ include "keycloak.fullname" . }}-themes
    spec:
      accessModes: [ "ReadWriteOncePod" ]
      storageClassName: "efs-sc"
      resources:
        requests:
          storage: 2Gi

# Add additional volumes mounts, e. g. for custom themes
extraVolumeMounts: |
  - name: {{ include "keycloak.fullname" . }}-static-vol
    mountPath: /opt/keycloak/static
  - name: {{ include "keycloak.fullname" . }}-themes
    mountPath: /opt/keycloak/themes
```

I will submit a PR with the chart additions I am currently using for my case.

Thanks for such a great chart!
