### ISSUE TITLE
[keycloak:5.1.5] deployPostgres=false still deploys postgres

### ISSUE THREAD

**Issue by rblaine95** [codecentric/helm-charts#90]
Hi there

I'm having the same issue as #40, I've got `keycloak.persistence.deployPostgres=false` and yet postgres keeps getting deployed.

```sh
$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://localhost:8443
openshift v3.11.0+3b2d3b6-227
kubernetes v1.11.0+d4cacc0
```
```yaml
keycloak:
  persistence:
    deployPostgres: false
    dbVendor: postgres
    dbName: keycloak
    dbHost: kubedb-postgres
    dbPort: 5432
    dbUser: keycloak
    dbPassword: keycloak
```

Maybe I'm just missing something?
